# Generated by Django 3.0 on 2020-06-19 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='amount (dollars)')),
                ('client_secret', models.CharField(default='', max_length=512)),
                ('payment_intent_id', models.CharField(default='', max_length=512)),
                ('status', models.CharField(default='', max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_payment_operations', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
