# Generated by Django 3.0 on 2020-06-20 13:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20200620_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentoperation',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
