# Generated by Django 3.0 on 2020-06-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_paymentoperation_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentoperation',
            name='status',
            field=models.CharField(default='', max_length=512),
        ),
    ]
