# Generated by Django 3.0 on 2020-06-20 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_money'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='money',
        ),
    ]
