export const billingActionConstants = {
    GET_CURRENT_MONEY_REQUEST: 'BILLING_GET_CURRENT_MONEY_REQUEST',
    GET_CURRENT_MONEY_SUCCESS: 'BILLING_GET_CURRENT_MONEY_SUCCESS',
    GET_CURRENT_MONEY_ERROR: 'BILLING_GET_CURRENT_MONEY_ERROR',

    GET_TRANSACTIONS_LIST_REQUEST: 'BILLING_GET_TRANSACTIONS_LIST_REQUEST',
    GET_TRANSACTIONS_LIST_SUCCESS: 'BILLING_GET_TRANSACTIONS_LIST_SUCCESS',
    GET_TRANSACTIONS_LIST_ERROR: 'BILLING_GET_TRANSACTIONS_LIST_ERROR',
};