export const containerActionConstants = {
    CREATE_CONTAINER_REQUEST: 'MODEL_ACTION_CREATE_CONTAINER_REQUEST',
    CREATE_CONTAINER_SUCCESS: 'MODEL_ACTION_CREATE_CONTAINER_SUCCESS',
    CREATE_CONTAINER_FAILURE: 'MODEL_ACTION_CREATE_CONTAINER_FAILURE',

    GET_CONTAINIERS_REQUEST: 'MODEL_ACTION_GET_CONTAINIERS_REQUEST',
    GET_CONTAINIERS_SUCCESS: 'MODEL_ACTION_GET_CONTAINIERS_SUCCESS',
    GET_CONTAINIERS_FAILURE: 'MODEL_ACTION_GET_CONTAINIERS_FAILURE',

    UPDATE_CONTAINER_REQUEST: 'MODEL_ACTION_UPDATE_CONTAINER_REQUEST',
    UPDATE_CONTAINER_SUCCESS: 'MODEL_ACTION_UPDATE_CONTAINER_SUCCESS',
    UPDATE_CONTAINER_FAILURE: 'MODEL_ACTION_UPDATE_CONTAINER_FAILURE',

    DELETE_CONTAINER_REQUEST: 'MODEL_ACTION_DELETE_CONTAINER_REQUEST',
    DELETE_CONTAINER_SUCCESS: 'MODEL_ACTION_DELETE_CONTAINER_SUCCESS',
    DELETE_CONTAINER_FAILURE: 'MODEL_ACTION_DELETE_CONTAINER_FAILURE',
};