export const functionActionConstants = {
    DELETE_FUNC_REQUEST: 'FUNC_ACTION_DELETE_FUNC_REQUEST',
    DELETE_FUNC_SUCCESS: 'FUNC_ACTION_DELETE_FUNC_SUCCESS',
    DELETE_FUNC_FAILURE: 'FUNC_ACTION_DELETE_FUNC_FAILURE',

    GET_FUNCS_REQUEST: 'FUNC_ACTION_GET_FUNCS_REQUEST',
    GET_FUNCS_SUCCESS: 'FUNC_ACTION_GET_FUNCS_SUCCESS',
    GET_FUNCS_FAILURE: 'FUNC_ACTION_GET_FUNCS_FAILURE',
};