export const metricsActionConstants = {
    GET_METRICS_REQUEST: 'METRICS_ACTION_GET_METRICS_REQUEST',
    GET_METRICS_SUCCESS: 'METRICS_ACTION_GET_METRICS_SUCCESS',
    GET_METRICS_FAILURE: 'METRICS_ACTION_GET_METRICS_FAILURE',
};