export const userActionConstants = {
    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    LOGOUT: 'USERS_LOGOUT',

    CURRENT_USER_INFO_SUCCESS: 'USERS_CURRENT_USER_INFO_SUCCESS',

    GET_CURRENT_MONEY_REQUEST: 'USERS_GET_CURRENT_MONEY_REQUEST',
    GET_CURRENT_MONEY_SUCCESS: 'USERS_GET_CURRENT_MONEY_SUCCESS',
    GET_CURRENT_MONEY_ERROR: 'USERS_GET_CURRENT_MONEY_ERROR',
};