# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import tesseract_pb2 as tesseract__pb2


class TesseractStub(object):
    """The Tesseract service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Apply = channel.unary_unary(
                '/tesseract.Tesseract/Apply',
                request_serializer=tesseract__pb2.ApplyRequest.SerializeToString,
                response_deserializer=tesseract__pb2.ApplyResponse.FromString,
                )
        self.GetStatus = channel.unary_unary(
                '/tesseract.Tesseract/GetStatus',
                request_serializer=tesseract__pb2.GetStatusRequest.SerializeToString,
                response_deserializer=tesseract__pb2.GetStatusResponse.FromString,
                )
        self.Delete = channel.unary_unary(
                '/tesseract.Tesseract/Delete',
                request_serializer=tesseract__pb2.DeleteRequest.SerializeToString,
                response_deserializer=tesseract__pb2.DeleteResponse.FromString,
                )


class TesseractServicer(object):
    """The Tesseract service definition.
    """

    def Apply(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TesseractServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Apply': grpc.unary_unary_rpc_method_handler(
                    servicer.Apply,
                    request_deserializer=tesseract__pb2.ApplyRequest.FromString,
                    response_serializer=tesseract__pb2.ApplyResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=tesseract__pb2.GetStatusRequest.FromString,
                    response_serializer=tesseract__pb2.GetStatusResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=tesseract__pb2.DeleteRequest.FromString,
                    response_serializer=tesseract__pb2.DeleteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tesseract.Tesseract', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Tesseract(object):
    """The Tesseract service definition.
    """

    @staticmethod
    def Apply(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tesseract.Tesseract/Apply',
            tesseract__pb2.ApplyRequest.SerializeToString,
            tesseract__pb2.ApplyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tesseract.Tesseract/GetStatus',
            tesseract__pb2.GetStatusRequest.SerializeToString,
            tesseract__pb2.GetStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tesseract.Tesseract/Delete',
            tesseract__pb2.DeleteRequest.SerializeToString,
            tesseract__pb2.DeleteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
