// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.11.2
// source: rhino.proto

package Rhino

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FunctionID string `protobuf:"bytes,1,opt,name=FunctionID,proto3" json:"FunctionID,omitempty"`
	Data       []byte `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rhino_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rhino_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_rhino_proto_rawDescGZIP(), []int{0}
}

func (x *RunRequest) GetFunctionID() string {
	if x != nil {
		return x.FunctionID
	}
	return ""
}

func (x *RunRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type RunReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *RunReply) Reset() {
	*x = RunReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rhino_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunReply) ProtoMessage() {}

func (x *RunReply) ProtoReflect() protoreflect.Message {
	mi := &file_rhino_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunReply.ProtoReflect.Descriptor instead.
func (*RunReply) Descriptor() ([]byte, []int) {
	return file_rhino_proto_rawDescGZIP(), []int{1}
}

func (x *RunReply) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_rhino_proto protoreflect.FileDescriptor

var file_rhino_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x72, 0x68, 0x69, 0x6e, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x52,
	0x68, 0x69, 0x6e, 0x6f, 0x22, 0x40, 0x0a, 0x0a, 0x52, 0x75, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x1e, 0x0a, 0x08, 0x52, 0x75, 0x6e, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x32, 0x32, 0x0a, 0x05, 0x52, 0x68, 0x69, 0x6e, 0x6f, 0x12,
	0x29, 0x0a, 0x03, 0x52, 0x75, 0x6e, 0x12, 0x11, 0x2e, 0x52, 0x68, 0x69, 0x6e, 0x6f, 0x2e, 0x52,
	0x75, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x52, 0x68, 0x69, 0x6e,
	0x6f, 0x2e, 0x52, 0x75, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_rhino_proto_rawDescOnce sync.Once
	file_rhino_proto_rawDescData = file_rhino_proto_rawDesc
)

func file_rhino_proto_rawDescGZIP() []byte {
	file_rhino_proto_rawDescOnce.Do(func() {
		file_rhino_proto_rawDescData = protoimpl.X.CompressGZIP(file_rhino_proto_rawDescData)
	})
	return file_rhino_proto_rawDescData
}

var file_rhino_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rhino_proto_goTypes = []interface{}{
	(*RunRequest)(nil), // 0: Rhino.RunRequest
	(*RunReply)(nil),   // 1: Rhino.RunReply
}
var file_rhino_proto_depIdxs = []int32{
	0, // 0: Rhino.Rhino.Run:input_type -> Rhino.RunRequest
	1, // 1: Rhino.Rhino.Run:output_type -> Rhino.RunReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rhino_proto_init() }
func file_rhino_proto_init() {
	if File_rhino_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rhino_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rhino_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rhino_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rhino_proto_goTypes,
		DependencyIndexes: file_rhino_proto_depIdxs,
		MessageInfos:      file_rhino_proto_msgTypes,
	}.Build()
	File_rhino_proto = out.File
	file_rhino_proto_rawDesc = nil
	file_rhino_proto_goTypes = nil
	file_rhino_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RhinoClient is the client API for Rhino service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RhinoClient interface {
	Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunReply, error)
}

type rhinoClient struct {
	cc grpc.ClientConnInterface
}

func NewRhinoClient(cc grpc.ClientConnInterface) RhinoClient {
	return &rhinoClient{cc}
}

func (c *rhinoClient) Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunReply, error) {
	out := new(RunReply)
	err := c.cc.Invoke(ctx, "/Rhino.Rhino/Run", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RhinoServer is the server API for Rhino service.
type RhinoServer interface {
	Run(context.Context, *RunRequest) (*RunReply, error)
}

// UnimplementedRhinoServer can be embedded to have forward compatible implementations.
type UnimplementedRhinoServer struct {
}

func (*UnimplementedRhinoServer) Run(context.Context, *RunRequest) (*RunReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Run not implemented")
}

func RegisterRhinoServer(s *grpc.Server, srv RhinoServer) {
	s.RegisterService(&_Rhino_serviceDesc, srv)
}

func _Rhino_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RhinoServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Rhino.Rhino/Run",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RhinoServer).Run(ctx, req.(*RunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Rhino_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Rhino.Rhino",
	HandlerType: (*RhinoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Run",
			Handler:    _Rhino_Run_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rhino.proto",
}
