// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package grpc

import (
	"github.com/go-kit/kit/transport/grpc"

	"ardea/pkg/endpoint"
	pb "ardea/pkg/grpc/pb"
)

// NewGRPCServer makes a set of endpoints available as a gRPC AddServer
type grpcServer struct {
	createModel      grpc.Handler
	getModel         grpc.Handler
	getModelByName   grpc.Handler
	updateModelState grpc.Handler
	updateModelPath  grpc.Handler
	listModels       grpc.Handler
}

func NewGRPCServer(endpoints endpoint.Endpoints, options map[string][]grpc.ServerOption) pb.ArdeaServer {
	return &grpcServer{
		createModel:      makeCreateModelHandler(endpoints, options["CreateModel"]),
		getModel:         makeGetModelHandler(endpoints, options["GetModel"]),
		getModelByName:   makeGetModelByNameHandler(endpoints, options["GetModelByName"]),
		updateModelPath:  makeUpdateModelPathHandler(endpoints, options["UpdateModelPath"]),
		updateModelState: makeUpdateModelStateHandler(endpoints, options["UpdateModelState"]),
		listModels:       makeListModelsHandler(endpoints, options["ListModels"]),
	}
}
