// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: ardea.proto

package ardea

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValueType int32

const (
	ValueType_UNKNOWN    ValueType = 0
	ValueType_FLOAT16    ValueType = 1
	ValueType_FLOAT32    ValueType = 2
	ValueType_FLOAT64    ValueType = 3
	ValueType_UINT8      ValueType = 4
	ValueType_UINT16     ValueType = 5
	ValueType_UINT32     ValueType = 6
	ValueType_UINT64     ValueType = 7
	ValueType_INT8       ValueType = 8
	ValueType_INT16      ValueType = 9
	ValueType_INT32      ValueType = 10
	ValueType_INT64      ValueType = 11
	ValueType_COMPLEX64  ValueType = 12
	ValueType_COMPLEX128 ValueType = 13
)

// Enum value maps for ValueType.
var (
	ValueType_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "FLOAT16",
		2:  "FLOAT32",
		3:  "FLOAT64",
		4:  "UINT8",
		5:  "UINT16",
		6:  "UINT32",
		7:  "UINT64",
		8:  "INT8",
		9:  "INT16",
		10: "INT32",
		11: "INT64",
		12: "COMPLEX64",
		13: "COMPLEX128",
	}
	ValueType_value = map[string]int32{
		"UNKNOWN":    0,
		"FLOAT16":    1,
		"FLOAT32":    2,
		"FLOAT64":    3,
		"UINT8":      4,
		"UINT16":     5,
		"UINT32":     6,
		"UINT64":     7,
		"INT8":       8,
		"INT16":      9,
		"INT32":      10,
		"INT64":      11,
		"COMPLEX64":  12,
		"COMPLEX128": 13,
	}
)

func (x ValueType) Enum() *ValueType {
	p := new(ValueType)
	*p = x
	return p
}

func (x ValueType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValueType) Descriptor() protoreflect.EnumDescriptor {
	return file_ardea_proto_enumTypes[0].Descriptor()
}

func (ValueType) Type() protoreflect.EnumType {
	return &file_ardea_proto_enumTypes[0]
}

func (x ValueType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValueType.Descriptor instead.
func (ValueType) EnumDescriptor() ([]byte, []int) {
	return file_ardea_proto_rawDescGZIP(), []int{0}
}

type ModelState int32

const (
	ModelState_STATE_UNKNOWN    ModelState = 0
	ModelState_STATE_INIT       ModelState = 1
	ModelState_STATE_PROCESSING ModelState = 2
	ModelState_STATE_READY      ModelState = 3
	ModelState_STATE_INVALID    ModelState = 4
	ModelState_STATE_DELETED    ModelState = 5
)

// Enum value maps for ModelState.
var (
	ModelState_name = map[int32]string{
		0: "STATE_UNKNOWN",
		1: "STATE_INIT",
		2: "STATE_PROCESSING",
		3: "STATE_READY",
		4: "STATE_INVALID",
		5: "STATE_DELETED",
	}
	ModelState_value = map[string]int32{
		"STATE_UNKNOWN":    0,
		"STATE_INIT":       1,
		"STATE_PROCESSING": 2,
		"STATE_READY":      3,
		"STATE_INVALID":    4,
		"STATE_DELETED":    5,
	}
)

func (x ModelState) Enum() *ModelState {
	p := new(ModelState)
	*p = x
	return p
}

func (x ModelState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ModelState) Descriptor() protoreflect.EnumDescriptor {
	return file_ardea_proto_enumTypes[1].Descriptor()
}

func (ModelState) Type() protoreflect.EnumType {
	return &file_ardea_proto_enumTypes[1]
}

func (x ModelState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ModelState.Descriptor instead.
func (ModelState) EnumDescriptor() ([]byte, []int) {
	return file_ardea_proto_rawDescGZIP(), []int{1}
}

type NullInt64 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value   int64 `protobuf:"varint,1,opt,name=Value,proto3" json:"Value,omitempty"`
	IsValid bool  `protobuf:"varint,2,opt,name=IsValid,proto3" json:"IsValid,omitempty"`
}

func (x *NullInt64) Reset() {
	*x = NullInt64{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ardea_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NullInt64) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullInt64) ProtoMessage() {}

func (x *NullInt64) ProtoReflect() protoreflect.Message {
	mi := &file_ardea_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullInt64.ProtoReflect.Descriptor instead.
func (*NullInt64) Descriptor() ([]byte, []int) {
	return file_ardea_proto_rawDescGZIP(), []int{0}
}

func (x *NullInt64) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *NullInt64) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

type Shape struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []*NullInt64 `protobuf:"bytes,1,rep,name=Value,proto3" json:"Value,omitempty"`
}

func (x *Shape) Reset() {
	*x = Shape{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ardea_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Shape) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shape) ProtoMessage() {}

func (x *Shape) ProtoReflect() protoreflect.Message {
	mi := &file_ardea_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shape.ProtoReflect.Descriptor instead.
func (*Shape) Descriptor() ([]byte, []int) {
	return file_ardea_proto_rawDescGZIP(), []int{1}
}

func (x *Shape) GetValue() []*NullInt64 {
	if x != nil {
		return x.Value
	}
	return nil
}

type Model struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID          string     `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	OwnerID     string     `protobuf:"bytes,2,opt,name=OwnerID,proto3" json:"OwnerID,omitempty"`
	State       ModelState `protobuf:"varint,3,opt,name=State,proto3,enum=ardea.ModelState" json:"State,omitempty"`
	InputShape  []*Shape   `protobuf:"bytes,4,rep,name=InputShape,proto3" json:"InputShape,omitempty"`
	OutputShape []*Shape   `protobuf:"bytes,5,rep,name=OutputShape,proto3" json:"OutputShape,omitempty"`
	Path        string     `protobuf:"bytes,6,opt,name=Path,proto3" json:"Path,omitempty"`
	Name        string     `protobuf:"bytes,7,opt,name=Name,proto3" json:"Name,omitempty"`
	Type        ValueType  `protobuf:"varint,8,opt,name=Type,proto3,enum=ardea.ValueType" json:"Type,omitempty"`
	ErrStrSet   bool       `protobuf:"varint,9,opt,name=ErrStrSet,proto3" json:"ErrStrSet,omitempty"`
	ErrStr      string     `protobuf:"bytes,10,opt,name=ErrStr,proto3" json:"ErrStr,omitempty"`
}

func (x *Model) Reset() {
	*x = Model{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ardea_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Model) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model) ProtoMessage() {}

func (x *Model) ProtoReflect() protoreflect.Message {
	mi := &file_ardea_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Model.ProtoReflect.Descriptor instead.
func (*Model) Descriptor() ([]byte, []int) {
	return file_ardea_proto_rawDescGZIP(), []int{2}
}

func (x *Model) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Model) GetOwnerID() string {
	if x != nil {
		return x.OwnerID
	}
	return ""
}

func (x *Model) GetState() ModelState {
	if x != nil {
		return x.State
	}
	return ModelState_STATE_UNKNOWN
}

func (x *Model) GetInputShape() []*Shape {
	if x != nil {
		return x.InputShape
	}
	return nil
}

func (x *Model) GetOutputShape() []*Shape {
	if x != nil {
		return x.OutputShape
	}
	return nil
}

func (x *Model) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Model) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Model) GetType() ValueType {
	if x != nil {
		return x.Type
	}
	return ValueType_UNKNOWN
}

func (x *Model) GetErrStrSet() bool {
	if x != nil {
		return x.ErrStrSet
	}
	return false
}

func (x *Model) GetErrStr() string {
	if x != nil {
		return x.ErrStr
	}
	return ""
}

type CreateModelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OwnerID     string    `protobuf:"bytes,1,opt,name=OwnerID,proto3" json:"OwnerID,omitempty"`
	Name        string    `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	InputShape  []*Shape  `protobuf:"bytes,3,rep,name=InputShape,proto3" json:"InputShape,omitempty"`
	OutputShape []*Shape  `protobuf:"bytes,4,rep,name=OutputShape,proto3" json:"OutputShape,omitempty"`
	Type        ValueType `protobuf:"varint,5,opt,name=Type,proto3,enum=ardea.ValueType" json:"Type,omitempty"`
}

func (x *CreateModelRequest) Reset() {
	*x = CreateModelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ardea_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateModelRequest) ProtoMessage() {}

func (x *CreateModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ardea_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateModelRequest.ProtoReflect.Descriptor instead.
func (*CreateModelRequest) Descriptor() ([]byte, []int) {
	return file_ardea_proto_rawDescGZIP(), []int{3}
}

func (x *CreateModelRequest) GetOwnerID() string {
	if x != nil {
		return x.OwnerID
	}
	return ""
}

func (x *CreateModelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateModelRequest) GetInputShape() []*Shape {
	if x != nil {
		return x.InputShape
	}
	return nil
}

func (x *CreateModelRequest) GetOutputShape() []*Shape {
	if x != nil {
		return x.OutputShape
	}
	return nil
}

func (x *CreateModelRequest) GetType() ValueType {
	if x != nil {
		return x.Type
	}
	return ValueType_UNKNOWN
}

type CreateModelReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Model *Model `protobuf:"bytes,1,opt,name=Model,proto3" json:"Model,omitempty"`
}

func (x *CreateModelReply) Reset() {
	*x = CreateModelReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ardea_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateModelReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateModelReply) ProtoMessage() {}

func (x *CreateModelReply) ProtoReflect() protoreflect.Message {
	mi := &file_ardea_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateModelReply.ProtoReflect.Descriptor instead.
func (*CreateModelReply) Descriptor() ([]byte, []int) {
	return file_ardea_proto_rawDescGZIP(), []int{4}
}

func (x *CreateModelReply) GetModel() *Model {
	if x != nil {
		return x.Model
	}
	return nil
}

type GetModelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *GetModelRequest) Reset() {
	*x = GetModelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ardea_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelRequest) ProtoMessage() {}

func (x *GetModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ardea_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelRequest.ProtoReflect.Descriptor instead.
func (*GetModelRequest) Descriptor() ([]byte, []int) {
	return file_ardea_proto_rawDescGZIP(), []int{5}
}

func (x *GetModelRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type GetModelByNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OwnerID string `protobuf:"bytes,1,opt,name=OwnerID,proto3" json:"OwnerID,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *GetModelByNameRequest) Reset() {
	*x = GetModelByNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ardea_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetModelByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelByNameRequest) ProtoMessage() {}

func (x *GetModelByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ardea_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelByNameRequest.ProtoReflect.Descriptor instead.
func (*GetModelByNameRequest) Descriptor() ([]byte, []int) {
	return file_ardea_proto_rawDescGZIP(), []int{6}
}

func (x *GetModelByNameRequest) GetOwnerID() string {
	if x != nil {
		return x.OwnerID
	}
	return ""
}

func (x *GetModelByNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetModelReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Model *Model `protobuf:"bytes,1,opt,name=Model,proto3" json:"Model,omitempty"`
}

func (x *GetModelReply) Reset() {
	*x = GetModelReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ardea_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetModelReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelReply) ProtoMessage() {}

func (x *GetModelReply) ProtoReflect() protoreflect.Message {
	mi := &file_ardea_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelReply.ProtoReflect.Descriptor instead.
func (*GetModelReply) Descriptor() ([]byte, []int) {
	return file_ardea_proto_rawDescGZIP(), []int{7}
}

func (x *GetModelReply) GetModel() *Model {
	if x != nil {
		return x.Model
	}
	return nil
}

type UpdateModelStateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID        string     `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	State     ModelState `protobuf:"varint,2,opt,name=State,proto3,enum=ardea.ModelState" json:"State,omitempty"`
	ErrStrSet bool       `protobuf:"varint,3,opt,name=ErrStrSet,proto3" json:"ErrStrSet,omitempty"`
	ErrStr    string     `protobuf:"bytes,4,opt,name=ErrStr,proto3" json:"ErrStr,omitempty"`
}

func (x *UpdateModelStateRequest) Reset() {
	*x = UpdateModelStateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ardea_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateModelStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateModelStateRequest) ProtoMessage() {}

func (x *UpdateModelStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ardea_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateModelStateRequest.ProtoReflect.Descriptor instead.
func (*UpdateModelStateRequest) Descriptor() ([]byte, []int) {
	return file_ardea_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateModelStateRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *UpdateModelStateRequest) GetState() ModelState {
	if x != nil {
		return x.State
	}
	return ModelState_STATE_UNKNOWN
}

func (x *UpdateModelStateRequest) GetErrStrSet() bool {
	if x != nil {
		return x.ErrStrSet
	}
	return false
}

func (x *UpdateModelStateRequest) GetErrStr() string {
	if x != nil {
		return x.ErrStr
	}
	return ""
}

type UpdateModelStateReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Model *Model `protobuf:"bytes,1,opt,name=Model,proto3" json:"Model,omitempty"`
}

func (x *UpdateModelStateReply) Reset() {
	*x = UpdateModelStateReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ardea_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateModelStateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateModelStateReply) ProtoMessage() {}

func (x *UpdateModelStateReply) ProtoReflect() protoreflect.Message {
	mi := &file_ardea_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateModelStateReply.ProtoReflect.Descriptor instead.
func (*UpdateModelStateReply) Descriptor() ([]byte, []int) {
	return file_ardea_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateModelStateReply) GetModel() *Model {
	if x != nil {
		return x.Model
	}
	return nil
}

type UpdateModelPathRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID   string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Path string `protobuf:"bytes,2,opt,name=Path,proto3" json:"Path,omitempty"`
}

func (x *UpdateModelPathRequest) Reset() {
	*x = UpdateModelPathRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ardea_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateModelPathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateModelPathRequest) ProtoMessage() {}

func (x *UpdateModelPathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ardea_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateModelPathRequest.ProtoReflect.Descriptor instead.
func (*UpdateModelPathRequest) Descriptor() ([]byte, []int) {
	return file_ardea_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateModelPathRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *UpdateModelPathRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ListModelsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OwnerID string `protobuf:"bytes,1,opt,name=OwnerID,proto3" json:"OwnerID,omitempty"`
}

func (x *ListModelsRequest) Reset() {
	*x = ListModelsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ardea_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsRequest) ProtoMessage() {}

func (x *ListModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ardea_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsRequest.ProtoReflect.Descriptor instead.
func (*ListModelsRequest) Descriptor() ([]byte, []int) {
	return file_ardea_proto_rawDescGZIP(), []int{11}
}

func (x *ListModelsRequest) GetOwnerID() string {
	if x != nil {
		return x.OwnerID
	}
	return ""
}

type ListModelsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Models []*Model `protobuf:"bytes,1,rep,name=Models,proto3" json:"Models,omitempty"`
}

func (x *ListModelsReply) Reset() {
	*x = ListModelsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ardea_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListModelsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsReply) ProtoMessage() {}

func (x *ListModelsReply) ProtoReflect() protoreflect.Message {
	mi := &file_ardea_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsReply.ProtoReflect.Descriptor instead.
func (*ListModelsReply) Descriptor() ([]byte, []int) {
	return file_ardea_proto_rawDescGZIP(), []int{12}
}

func (x *ListModelsReply) GetModels() []*Model {
	if x != nil {
		return x.Models
	}
	return nil
}

type UpdateModelPathReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Model *Model `protobuf:"bytes,1,opt,name=Model,proto3" json:"Model,omitempty"`
}

func (x *UpdateModelPathReply) Reset() {
	*x = UpdateModelPathReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ardea_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateModelPathReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateModelPathReply) ProtoMessage() {}

func (x *UpdateModelPathReply) ProtoReflect() protoreflect.Message {
	mi := &file_ardea_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateModelPathReply.ProtoReflect.Descriptor instead.
func (*UpdateModelPathReply) Descriptor() ([]byte, []int) {
	return file_ardea_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateModelPathReply) GetModel() *Model {
	if x != nil {
		return x.Model
	}
	return nil
}

var File_ardea_proto protoreflect.FileDescriptor

var file_ardea_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x61, 0x72, 0x64, 0x65, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x61,
	0x72, 0x64, 0x65, 0x61, 0x22, 0x3b, 0x0a, 0x09, 0x4e, 0x75, 0x6c, 0x6c, 0x49, 0x6e, 0x74, 0x36,
	0x34, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x49, 0x73, 0x56, 0x61, 0x6c,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x49, 0x73, 0x56, 0x61, 0x6c, 0x69,
	0x64, 0x22, 0x2f, 0x0a, 0x05, 0x53, 0x68, 0x61, 0x70, 0x65, 0x12, 0x26, 0x0a, 0x05, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x61, 0x72, 0x64, 0x65,
	0x61, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x52, 0x05, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0xbc, 0x02, 0x0a, 0x05, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07,
	0x4f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4f,
	0x77, 0x6e, 0x65, 0x72, 0x49, 0x44, 0x12, 0x27, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x61, 0x72, 0x64, 0x65, 0x61, 0x2e, 0x4d, 0x6f,
	0x64, 0x65, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12,
	0x2c, 0x0a, 0x0a, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x53, 0x68, 0x61, 0x70, 0x65, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x61, 0x72, 0x64, 0x65, 0x61, 0x2e, 0x53, 0x68, 0x61, 0x70,
	0x65, 0x52, 0x0a, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x53, 0x68, 0x61, 0x70, 0x65, 0x12, 0x2e, 0x0a,
	0x0b, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x53, 0x68, 0x61, 0x70, 0x65, 0x18, 0x05, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x61, 0x72, 0x64, 0x65, 0x61, 0x2e, 0x53, 0x68, 0x61, 0x70, 0x65,
	0x52, 0x0b, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x53, 0x68, 0x61, 0x70, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x50, 0x61, 0x74, 0x68, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x50, 0x61, 0x74,
	0x68, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x61, 0x72, 0x64, 0x65, 0x61, 0x2e, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x45,
	0x72, 0x72, 0x53, 0x74, 0x72, 0x53, 0x65, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09,
	0x45, 0x72, 0x72, 0x53, 0x74, 0x72, 0x53, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x45, 0x72, 0x72,
	0x53, 0x74, 0x72, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x45, 0x72, 0x72, 0x53, 0x74,
	0x72, 0x22, 0xc6, 0x01, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x77, 0x6e, 0x65,
	0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4f, 0x77, 0x6e, 0x65, 0x72,
	0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x0a, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x53,
	0x68, 0x61, 0x70, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x61, 0x72, 0x64,
	0x65, 0x61, 0x2e, 0x53, 0x68, 0x61, 0x70, 0x65, 0x52, 0x0a, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x53,
	0x68, 0x61, 0x70, 0x65, 0x12, 0x2e, 0x0a, 0x0b, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x53, 0x68,
	0x61, 0x70, 0x65, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x61, 0x72, 0x64, 0x65,
	0x61, 0x2e, 0x53, 0x68, 0x61, 0x70, 0x65, 0x52, 0x0b, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x53,
	0x68, 0x61, 0x70, 0x65, 0x12, 0x24, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x10, 0x2e, 0x61, 0x72, 0x64, 0x65, 0x61, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x22, 0x36, 0x0a, 0x10, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x22,
	0x0a, 0x05, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x61, 0x72, 0x64, 0x65, 0x61, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x05, 0x4d, 0x6f, 0x64,
	0x65, 0x6c, 0x22, 0x21, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x49, 0x44, 0x22, 0x45, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x33, 0x0a, 0x0d,
	0x47, 0x65, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x22, 0x0a,
	0x05, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x61,
	0x72, 0x64, 0x65, 0x61, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x05, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x22, 0x88, 0x01, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x27, 0x0a,
	0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x61,
	0x72, 0x64, 0x65, 0x61, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52,
	0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x45, 0x72, 0x72, 0x53, 0x74, 0x72,
	0x53, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x45, 0x72, 0x72, 0x53, 0x74,
	0x72, 0x53, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x45, 0x72, 0x72, 0x53, 0x74, 0x72, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x45, 0x72, 0x72, 0x53, 0x74, 0x72, 0x22, 0x3b, 0x0a, 0x15,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x22, 0x0a, 0x05, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x61, 0x72, 0x64, 0x65, 0x61, 0x2e, 0x4d, 0x6f, 0x64,
	0x65, 0x6c, 0x52, 0x05, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x3c, 0x0a, 0x16, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x50, 0x61, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x50, 0x61, 0x74, 0x68, 0x22, 0x2d, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x4d,
	0x6f, 0x64, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x4f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4f,
	0x77, 0x6e, 0x65, 0x72, 0x49, 0x44, 0x22, 0x37, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x6f,
	0x64, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x24, 0x0a, 0x06, 0x4d, 0x6f, 0x64,
	0x65, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x61, 0x72, 0x64, 0x65,
	0x61, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x06, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x22,
	0x3a, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x50, 0x61,
	0x74, 0x68, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x22, 0x0a, 0x05, 0x4d, 0x6f, 0x64, 0x65, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x61, 0x72, 0x64, 0x65, 0x61, 0x2e, 0x4d,
	0x6f, 0x64, 0x65, 0x6c, 0x52, 0x05, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x2a, 0xb8, 0x01, 0x0a, 0x09,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b,
	0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x46, 0x4c, 0x4f, 0x41, 0x54, 0x31,
	0x36, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x46, 0x4c, 0x4f, 0x41, 0x54, 0x33, 0x32, 0x10, 0x02,
	0x12, 0x0b, 0x0a, 0x07, 0x46, 0x4c, 0x4f, 0x41, 0x54, 0x36, 0x34, 0x10, 0x03, 0x12, 0x09, 0x0a,
	0x05, 0x55, 0x49, 0x4e, 0x54, 0x38, 0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x49, 0x4e, 0x54,
	0x31, 0x36, 0x10, 0x05, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x49, 0x4e, 0x54, 0x33, 0x32, 0x10, 0x06,
	0x12, 0x0a, 0x0a, 0x06, 0x55, 0x49, 0x4e, 0x54, 0x36, 0x34, 0x10, 0x07, 0x12, 0x08, 0x0a, 0x04,
	0x49, 0x4e, 0x54, 0x38, 0x10, 0x08, 0x12, 0x09, 0x0a, 0x05, 0x49, 0x4e, 0x54, 0x31, 0x36, 0x10,
	0x09, 0x12, 0x09, 0x0a, 0x05, 0x49, 0x4e, 0x54, 0x33, 0x32, 0x10, 0x0a, 0x12, 0x09, 0x0a, 0x05,
	0x49, 0x4e, 0x54, 0x36, 0x34, 0x10, 0x0b, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x4f, 0x4d, 0x50, 0x4c,
	0x45, 0x58, 0x36, 0x34, 0x10, 0x0c, 0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x4f, 0x4d, 0x50, 0x4c, 0x45,
	0x58, 0x31, 0x32, 0x38, 0x10, 0x0d, 0x2a, 0x7c, 0x0a, 0x0a, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x55, 0x4e,
	0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x54, 0x41, 0x54, 0x45,
	0x5f, 0x49, 0x4e, 0x49, 0x54, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x53, 0x54, 0x41, 0x54, 0x45,
	0x5f, 0x50, 0x52, 0x4f, 0x43, 0x45, 0x53, 0x53, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x0f, 0x0a,
	0x0b, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x52, 0x45, 0x41, 0x44, 0x59, 0x10, 0x03, 0x12, 0x11,
	0x0a, 0x0d, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10,
	0x04, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x44, 0x45, 0x4c, 0x45, 0x54,
	0x45, 0x44, 0x10, 0x05, 0x32, 0xab, 0x03, 0x0a, 0x05, 0x41, 0x72, 0x64, 0x65, 0x61, 0x12, 0x41,
	0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x19, 0x2e,
	0x61, 0x72, 0x64, 0x65, 0x61, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x61, 0x72, 0x64, 0x65, 0x61,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x38, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x16, 0x2e,
	0x61, 0x72, 0x64, 0x65, 0x61, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x61, 0x72, 0x64, 0x65, 0x61, 0x2e, 0x47, 0x65,
	0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x44, 0x0a, 0x0e, 0x47,
	0x65, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x2e,
	0x61, 0x72, 0x64, 0x65, 0x61, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x42, 0x79,
	0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x61, 0x72,
	0x64, 0x65, 0x61, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x50, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1e, 0x2e, 0x61, 0x72, 0x64, 0x65, 0x61, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x61, 0x72, 0x64, 0x65, 0x61, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x4d, 0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x64,
	0x65, 0x6c, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1d, 0x2e, 0x61, 0x72, 0x64, 0x65, 0x61, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x50, 0x61, 0x74, 0x68, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x61, 0x72, 0x64, 0x65, 0x61, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x50, 0x61, 0x74, 0x68, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x3e, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73,
	0x12, 0x18, 0x2e, 0x61, 0x72, 0x64, 0x65, 0x61, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x6f, 0x64,
	0x65, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x61, 0x72, 0x64,
	0x65, 0x61, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ardea_proto_rawDescOnce sync.Once
	file_ardea_proto_rawDescData = file_ardea_proto_rawDesc
)

func file_ardea_proto_rawDescGZIP() []byte {
	file_ardea_proto_rawDescOnce.Do(func() {
		file_ardea_proto_rawDescData = protoimpl.X.CompressGZIP(file_ardea_proto_rawDescData)
	})
	return file_ardea_proto_rawDescData
}

var file_ardea_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_ardea_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_ardea_proto_goTypes = []interface{}{
	(ValueType)(0),                  // 0: ardea.ValueType
	(ModelState)(0),                 // 1: ardea.ModelState
	(*NullInt64)(nil),               // 2: ardea.NullInt64
	(*Shape)(nil),                   // 3: ardea.Shape
	(*Model)(nil),                   // 4: ardea.Model
	(*CreateModelRequest)(nil),      // 5: ardea.CreateModelRequest
	(*CreateModelReply)(nil),        // 6: ardea.CreateModelReply
	(*GetModelRequest)(nil),         // 7: ardea.GetModelRequest
	(*GetModelByNameRequest)(nil),   // 8: ardea.GetModelByNameRequest
	(*GetModelReply)(nil),           // 9: ardea.GetModelReply
	(*UpdateModelStateRequest)(nil), // 10: ardea.UpdateModelStateRequest
	(*UpdateModelStateReply)(nil),   // 11: ardea.UpdateModelStateReply
	(*UpdateModelPathRequest)(nil),  // 12: ardea.UpdateModelPathRequest
	(*ListModelsRequest)(nil),       // 13: ardea.ListModelsRequest
	(*ListModelsReply)(nil),         // 14: ardea.ListModelsReply
	(*UpdateModelPathReply)(nil),    // 15: ardea.UpdateModelPathReply
}
var file_ardea_proto_depIdxs = []int32{
	2,  // 0: ardea.Shape.Value:type_name -> ardea.NullInt64
	1,  // 1: ardea.Model.State:type_name -> ardea.ModelState
	3,  // 2: ardea.Model.InputShape:type_name -> ardea.Shape
	3,  // 3: ardea.Model.OutputShape:type_name -> ardea.Shape
	0,  // 4: ardea.Model.Type:type_name -> ardea.ValueType
	3,  // 5: ardea.CreateModelRequest.InputShape:type_name -> ardea.Shape
	3,  // 6: ardea.CreateModelRequest.OutputShape:type_name -> ardea.Shape
	0,  // 7: ardea.CreateModelRequest.Type:type_name -> ardea.ValueType
	4,  // 8: ardea.CreateModelReply.Model:type_name -> ardea.Model
	4,  // 9: ardea.GetModelReply.Model:type_name -> ardea.Model
	1,  // 10: ardea.UpdateModelStateRequest.State:type_name -> ardea.ModelState
	4,  // 11: ardea.UpdateModelStateReply.Model:type_name -> ardea.Model
	4,  // 12: ardea.ListModelsReply.Models:type_name -> ardea.Model
	4,  // 13: ardea.UpdateModelPathReply.Model:type_name -> ardea.Model
	5,  // 14: ardea.Ardea.CreateModel:input_type -> ardea.CreateModelRequest
	7,  // 15: ardea.Ardea.GetModel:input_type -> ardea.GetModelRequest
	8,  // 16: ardea.Ardea.GetModelByName:input_type -> ardea.GetModelByNameRequest
	10, // 17: ardea.Ardea.UpdateModelState:input_type -> ardea.UpdateModelStateRequest
	12, // 18: ardea.Ardea.UpdateModelPath:input_type -> ardea.UpdateModelPathRequest
	13, // 19: ardea.Ardea.ListModels:input_type -> ardea.ListModelsRequest
	6,  // 20: ardea.Ardea.CreateModel:output_type -> ardea.CreateModelReply
	9,  // 21: ardea.Ardea.GetModel:output_type -> ardea.GetModelReply
	9,  // 22: ardea.Ardea.GetModelByName:output_type -> ardea.GetModelReply
	11, // 23: ardea.Ardea.UpdateModelState:output_type -> ardea.UpdateModelStateReply
	15, // 24: ardea.Ardea.UpdateModelPath:output_type -> ardea.UpdateModelPathReply
	14, // 25: ardea.Ardea.ListModels:output_type -> ardea.ListModelsReply
	20, // [20:26] is the sub-list for method output_type
	14, // [14:20] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_ardea_proto_init() }
func file_ardea_proto_init() {
	if File_ardea_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ardea_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NullInt64); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ardea_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Shape); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ardea_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Model); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ardea_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateModelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ardea_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateModelReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ardea_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetModelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ardea_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetModelByNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ardea_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetModelReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ardea_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateModelStateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ardea_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateModelStateReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ardea_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateModelPathRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ardea_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListModelsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ardea_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListModelsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ardea_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateModelPathReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ardea_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ardea_proto_goTypes,
		DependencyIndexes: file_ardea_proto_depIdxs,
		EnumInfos:         file_ardea_proto_enumTypes,
		MessageInfos:      file_ardea_proto_msgTypes,
	}.Build()
	File_ardea_proto = out.File
	file_ardea_proto_rawDesc = nil
	file_ardea_proto_goTypes = nil
	file_ardea_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ArdeaClient is the client API for Ardea service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ArdeaClient interface {
	CreateModel(ctx context.Context, in *CreateModelRequest, opts ...grpc.CallOption) (*CreateModelReply, error)
	GetModel(ctx context.Context, in *GetModelRequest, opts ...grpc.CallOption) (*GetModelReply, error)
	GetModelByName(ctx context.Context, in *GetModelByNameRequest, opts ...grpc.CallOption) (*GetModelReply, error)
	UpdateModelState(ctx context.Context, in *UpdateModelStateRequest, opts ...grpc.CallOption) (*UpdateModelStateReply, error)
	UpdateModelPath(ctx context.Context, in *UpdateModelPathRequest, opts ...grpc.CallOption) (*UpdateModelPathReply, error)
	ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsReply, error)
}

type ardeaClient struct {
	cc grpc.ClientConnInterface
}

func NewArdeaClient(cc grpc.ClientConnInterface) ArdeaClient {
	return &ardeaClient{cc}
}

func (c *ardeaClient) CreateModel(ctx context.Context, in *CreateModelRequest, opts ...grpc.CallOption) (*CreateModelReply, error) {
	out := new(CreateModelReply)
	err := c.cc.Invoke(ctx, "/ardea.Ardea/CreateModel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ardeaClient) GetModel(ctx context.Context, in *GetModelRequest, opts ...grpc.CallOption) (*GetModelReply, error) {
	out := new(GetModelReply)
	err := c.cc.Invoke(ctx, "/ardea.Ardea/GetModel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ardeaClient) GetModelByName(ctx context.Context, in *GetModelByNameRequest, opts ...grpc.CallOption) (*GetModelReply, error) {
	out := new(GetModelReply)
	err := c.cc.Invoke(ctx, "/ardea.Ardea/GetModelByName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ardeaClient) UpdateModelState(ctx context.Context, in *UpdateModelStateRequest, opts ...grpc.CallOption) (*UpdateModelStateReply, error) {
	out := new(UpdateModelStateReply)
	err := c.cc.Invoke(ctx, "/ardea.Ardea/UpdateModelState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ardeaClient) UpdateModelPath(ctx context.Context, in *UpdateModelPathRequest, opts ...grpc.CallOption) (*UpdateModelPathReply, error) {
	out := new(UpdateModelPathReply)
	err := c.cc.Invoke(ctx, "/ardea.Ardea/UpdateModelPath", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ardeaClient) ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsReply, error) {
	out := new(ListModelsReply)
	err := c.cc.Invoke(ctx, "/ardea.Ardea/ListModels", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArdeaServer is the server API for Ardea service.
type ArdeaServer interface {
	CreateModel(context.Context, *CreateModelRequest) (*CreateModelReply, error)
	GetModel(context.Context, *GetModelRequest) (*GetModelReply, error)
	GetModelByName(context.Context, *GetModelByNameRequest) (*GetModelReply, error)
	UpdateModelState(context.Context, *UpdateModelStateRequest) (*UpdateModelStateReply, error)
	UpdateModelPath(context.Context, *UpdateModelPathRequest) (*UpdateModelPathReply, error)
	ListModels(context.Context, *ListModelsRequest) (*ListModelsReply, error)
}

// UnimplementedArdeaServer can be embedded to have forward compatible implementations.
type UnimplementedArdeaServer struct {
}

func (*UnimplementedArdeaServer) CreateModel(context.Context, *CreateModelRequest) (*CreateModelReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateModel not implemented")
}
func (*UnimplementedArdeaServer) GetModel(context.Context, *GetModelRequest) (*GetModelReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetModel not implemented")
}
func (*UnimplementedArdeaServer) GetModelByName(context.Context, *GetModelByNameRequest) (*GetModelReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetModelByName not implemented")
}
func (*UnimplementedArdeaServer) UpdateModelState(context.Context, *UpdateModelStateRequest) (*UpdateModelStateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateModelState not implemented")
}
func (*UnimplementedArdeaServer) UpdateModelPath(context.Context, *UpdateModelPathRequest) (*UpdateModelPathReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateModelPath not implemented")
}
func (*UnimplementedArdeaServer) ListModels(context.Context, *ListModelsRequest) (*ListModelsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListModels not implemented")
}

func RegisterArdeaServer(s *grpc.Server, srv ArdeaServer) {
	s.RegisterService(&_Ardea_serviceDesc, srv)
}

func _Ardea_CreateModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArdeaServer).CreateModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ardea.Ardea/CreateModel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArdeaServer).CreateModel(ctx, req.(*CreateModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ardea_GetModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArdeaServer).GetModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ardea.Ardea/GetModel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArdeaServer).GetModel(ctx, req.(*GetModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ardea_GetModelByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModelByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArdeaServer).GetModelByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ardea.Ardea/GetModelByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArdeaServer).GetModelByName(ctx, req.(*GetModelByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ardea_UpdateModelState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateModelStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArdeaServer).UpdateModelState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ardea.Ardea/UpdateModelState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArdeaServer).UpdateModelState(ctx, req.(*UpdateModelStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ardea_UpdateModelPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateModelPathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArdeaServer).UpdateModelPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ardea.Ardea/UpdateModelPath",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArdeaServer).UpdateModelPath(ctx, req.(*UpdateModelPathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ardea_ListModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArdeaServer).ListModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ardea.Ardea/ListModels",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArdeaServer).ListModels(ctx, req.(*ListModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Ardea_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ardea.Ardea",
	HandlerType: (*ArdeaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateModel",
			Handler:    _Ardea_CreateModel_Handler,
		},
		{
			MethodName: "GetModel",
			Handler:    _Ardea_GetModel_Handler,
		},
		{
			MethodName: "GetModelByName",
			Handler:    _Ardea_GetModelByName_Handler,
		},
		{
			MethodName: "UpdateModelState",
			Handler:    _Ardea_UpdateModelState_Handler,
		},
		{
			MethodName: "UpdateModelPath",
			Handler:    _Ardea_UpdateModelPath_Handler,
		},
		{
			MethodName: "ListModels",
			Handler:    _Ardea_ListModels_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ardea.proto",
}
