# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gorilla.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gorilla.proto',
  package='gorilla',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rgorilla.proto\x12\x07gorilla\"o\n\x05\x44\x65lta\x12\x0c\n\x04\x44\x61te\x18\x01 \x01(\x03\x12\x10\n\x08\x43\x61tegory\x18\x02 \x01(\t\x12\x0f\n\x07\x42\x61lance\x18\x03 \x01(\x01\x12\x0f\n\x07OwnerID\x18\x04 \x01(\t\x12\x10\n\x08ObjectID\x18\x05 \x01(\t\x12\x12\n\nObjectType\x18\x06 \x01(\t\"2\n\x10\x41\x64\x64\x44\x65ltasRequest\x12\x1e\n\x06\x44\x65ltas\x18\x01 \x03(\x0b\x32\x0e.gorilla.Delta\"\x13\n\x11\x41\x64\x64\x44\x65ltasResponse\"\x85\x01\n\x10GetDeltasRequest\x12\x0f\n\x07OwnerID\x18\x01 \x01(\t\x12\x10\n\x08ObjectID\x18\x02 \x01(\t\x12\x12\n\nObjectType\x18\x03 \x01(\t\x12\x11\n\tFirstDate\x18\x04 \x01(\x03\x12\x10\n\x08LastDate\x18\x05 \x01(\x03\x12\x15\n\rUseCategories\x18\x06 \x01(\x08\"3\n\x11GetDeltasResponse\x12\x1e\n\x06\x44\x65ltas\x18\x01 \x03(\x0b\x32\x0e.gorilla.Delta\"$\n\x11GetBalanceRequest\x12\x0f\n\x07OwnerID\x18\x01 \x01(\t\"%\n\x12GetBalanceResponse\x12\x0f\n\x07\x42\x61lance\x18\x01 \x01(\x01\x32\xd8\x01\n\x07Gorilla\x12\x42\n\tAddDeltas\x12\x19.gorilla.AddDeltasRequest\x1a\x1a.gorilla.AddDeltasResponse\x12\x42\n\tGetDeltas\x12\x19.gorilla.GetDeltasRequest\x1a\x1a.gorilla.GetDeltasResponse\x12\x45\n\nGetBalance\x12\x1a.gorilla.GetBalanceRequest\x1a\x1b.gorilla.GetBalanceResponseb\x06proto3'
)




_DELTA = _descriptor.Descriptor(
  name='Delta',
  full_name='gorilla.Delta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Date', full_name='gorilla.Delta.Date', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Category', full_name='gorilla.Delta.Category', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Balance', full_name='gorilla.Delta.Balance', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='OwnerID', full_name='gorilla.Delta.OwnerID', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ObjectID', full_name='gorilla.Delta.ObjectID', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ObjectType', full_name='gorilla.Delta.ObjectType', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=137,
)


_ADDDELTASREQUEST = _descriptor.Descriptor(
  name='AddDeltasRequest',
  full_name='gorilla.AddDeltasRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Deltas', full_name='gorilla.AddDeltasRequest.Deltas', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=189,
)


_ADDDELTASRESPONSE = _descriptor.Descriptor(
  name='AddDeltasResponse',
  full_name='gorilla.AddDeltasResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=191,
  serialized_end=210,
)


_GETDELTASREQUEST = _descriptor.Descriptor(
  name='GetDeltasRequest',
  full_name='gorilla.GetDeltasRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='OwnerID', full_name='gorilla.GetDeltasRequest.OwnerID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ObjectID', full_name='gorilla.GetDeltasRequest.ObjectID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ObjectType', full_name='gorilla.GetDeltasRequest.ObjectType', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='FirstDate', full_name='gorilla.GetDeltasRequest.FirstDate', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='LastDate', full_name='gorilla.GetDeltasRequest.LastDate', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='UseCategories', full_name='gorilla.GetDeltasRequest.UseCategories', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=346,
)


_GETDELTASRESPONSE = _descriptor.Descriptor(
  name='GetDeltasResponse',
  full_name='gorilla.GetDeltasResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Deltas', full_name='gorilla.GetDeltasResponse.Deltas', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=348,
  serialized_end=399,
)


_GETBALANCEREQUEST = _descriptor.Descriptor(
  name='GetBalanceRequest',
  full_name='gorilla.GetBalanceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='OwnerID', full_name='gorilla.GetBalanceRequest.OwnerID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=401,
  serialized_end=437,
)


_GETBALANCERESPONSE = _descriptor.Descriptor(
  name='GetBalanceResponse',
  full_name='gorilla.GetBalanceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Balance', full_name='gorilla.GetBalanceResponse.Balance', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=439,
  serialized_end=476,
)

_ADDDELTASREQUEST.fields_by_name['Deltas'].message_type = _DELTA
_GETDELTASRESPONSE.fields_by_name['Deltas'].message_type = _DELTA
DESCRIPTOR.message_types_by_name['Delta'] = _DELTA
DESCRIPTOR.message_types_by_name['AddDeltasRequest'] = _ADDDELTASREQUEST
DESCRIPTOR.message_types_by_name['AddDeltasResponse'] = _ADDDELTASRESPONSE
DESCRIPTOR.message_types_by_name['GetDeltasRequest'] = _GETDELTASREQUEST
DESCRIPTOR.message_types_by_name['GetDeltasResponse'] = _GETDELTASRESPONSE
DESCRIPTOR.message_types_by_name['GetBalanceRequest'] = _GETBALANCEREQUEST
DESCRIPTOR.message_types_by_name['GetBalanceResponse'] = _GETBALANCERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Delta = _reflection.GeneratedProtocolMessageType('Delta', (_message.Message,), {
  'DESCRIPTOR' : _DELTA,
  '__module__' : 'gorilla_pb2'
  # @@protoc_insertion_point(class_scope:gorilla.Delta)
  })
_sym_db.RegisterMessage(Delta)

AddDeltasRequest = _reflection.GeneratedProtocolMessageType('AddDeltasRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDDELTASREQUEST,
  '__module__' : 'gorilla_pb2'
  # @@protoc_insertion_point(class_scope:gorilla.AddDeltasRequest)
  })
_sym_db.RegisterMessage(AddDeltasRequest)

AddDeltasResponse = _reflection.GeneratedProtocolMessageType('AddDeltasResponse', (_message.Message,), {
  'DESCRIPTOR' : _ADDDELTASRESPONSE,
  '__module__' : 'gorilla_pb2'
  # @@protoc_insertion_point(class_scope:gorilla.AddDeltasResponse)
  })
_sym_db.RegisterMessage(AddDeltasResponse)

GetDeltasRequest = _reflection.GeneratedProtocolMessageType('GetDeltasRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETDELTASREQUEST,
  '__module__' : 'gorilla_pb2'
  # @@protoc_insertion_point(class_scope:gorilla.GetDeltasRequest)
  })
_sym_db.RegisterMessage(GetDeltasRequest)

GetDeltasResponse = _reflection.GeneratedProtocolMessageType('GetDeltasResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETDELTASRESPONSE,
  '__module__' : 'gorilla_pb2'
  # @@protoc_insertion_point(class_scope:gorilla.GetDeltasResponse)
  })
_sym_db.RegisterMessage(GetDeltasResponse)

GetBalanceRequest = _reflection.GeneratedProtocolMessageType('GetBalanceRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETBALANCEREQUEST,
  '__module__' : 'gorilla_pb2'
  # @@protoc_insertion_point(class_scope:gorilla.GetBalanceRequest)
  })
_sym_db.RegisterMessage(GetBalanceRequest)

GetBalanceResponse = _reflection.GeneratedProtocolMessageType('GetBalanceResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETBALANCERESPONSE,
  '__module__' : 'gorilla_pb2'
  # @@protoc_insertion_point(class_scope:gorilla.GetBalanceResponse)
  })
_sym_db.RegisterMessage(GetBalanceResponse)



_GORILLA = _descriptor.ServiceDescriptor(
  name='Gorilla',
  full_name='gorilla.Gorilla',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=479,
  serialized_end=695,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddDeltas',
    full_name='gorilla.Gorilla.AddDeltas',
    index=0,
    containing_service=None,
    input_type=_ADDDELTASREQUEST,
    output_type=_ADDDELTASRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetDeltas',
    full_name='gorilla.Gorilla.GetDeltas',
    index=1,
    containing_service=None,
    input_type=_GETDELTASREQUEST,
    output_type=_GETDELTASRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetBalance',
    full_name='gorilla.Gorilla.GetBalance',
    index=2,
    containing_service=None,
    input_type=_GETBALANCEREQUEST,
    output_type=_GETBALANCERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GORILLA)

DESCRIPTOR.services_by_name['Gorilla'] = _GORILLA

# @@protoc_insertion_point(module_scope)
