// Code generated by protoc-gen-go. DO NOT EDIT.
// source: selachii.proto

package selachii

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ValueType int32

const (
	ValueType_UNKNOWN    ValueType = 0
	ValueType_FLOAT16    ValueType = 1
	ValueType_FLOAT32    ValueType = 2
	ValueType_FLOAT64    ValueType = 3
	ValueType_UINT8      ValueType = 4
	ValueType_UINT16     ValueType = 5
	ValueType_UINT32     ValueType = 6
	ValueType_UINT64     ValueType = 7
	ValueType_INT8       ValueType = 8
	ValueType_INT16      ValueType = 9
	ValueType_INT32      ValueType = 10
	ValueType_INT64      ValueType = 11
	ValueType_COMPLEX64  ValueType = 12
	ValueType_COMPLEX128 ValueType = 13
)

var ValueType_name = map[int32]string{
	0:  "UNKNOWN",
	1:  "FLOAT16",
	2:  "FLOAT32",
	3:  "FLOAT64",
	4:  "UINT8",
	5:  "UINT16",
	6:  "UINT32",
	7:  "UINT64",
	8:  "INT8",
	9:  "INT16",
	10: "INT32",
	11: "INT64",
	12: "COMPLEX64",
	13: "COMPLEX128",
}

var ValueType_value = map[string]int32{
	"UNKNOWN":    0,
	"FLOAT16":    1,
	"FLOAT32":    2,
	"FLOAT64":    3,
	"UINT8":      4,
	"UINT16":     5,
	"UINT32":     6,
	"UINT64":     7,
	"INT8":       8,
	"INT16":      9,
	"INT32":      10,
	"INT64":      11,
	"COMPLEX64":  12,
	"COMPLEX128": 13,
}

func (x ValueType) String() string {
	return proto.EnumName(ValueType_name, int32(x))
}

func (ValueType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_32f123e663c9e0f3, []int{0}
}

type Shape struct {
	Value                []int64  `protobuf:"varint,1,rep,packed,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Shape) Reset()         { *m = Shape{} }
func (m *Shape) String() string { return proto.CompactTextString(m) }
func (*Shape) ProtoMessage()    {}
func (*Shape) Descriptor() ([]byte, []int) {
	return fileDescriptor_32f123e663c9e0f3, []int{0}
}

func (m *Shape) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Shape.Unmarshal(m, b)
}
func (m *Shape) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Shape.Marshal(b, m, deterministic)
}
func (m *Shape) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Shape.Merge(m, src)
}
func (m *Shape) XXX_Size() int {
	return xxx_messageInfo_Shape.Size(m)
}
func (m *Shape) XXX_DiscardUnknown() {
	xxx_messageInfo_Shape.DiscardUnknown(m)
}

var xxx_messageInfo_Shape proto.InternalMessageInfo

func (m *Shape) GetValue() []int64 {
	if m != nil {
		return m.Value
	}
	return nil
}

type Tensor struct {
	Type                 ValueType `protobuf:"varint,1,opt,name=Type,proto3,enum=selachii.ValueType" json:"Type,omitempty"`
	Shape                *Shape    `protobuf:"bytes,2,opt,name=Shape,proto3" json:"Shape,omitempty"`
	Data                 []byte    `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Tensor) Reset()         { *m = Tensor{} }
func (m *Tensor) String() string { return proto.CompactTextString(m) }
func (*Tensor) ProtoMessage()    {}
func (*Tensor) Descriptor() ([]byte, []int) {
	return fileDescriptor_32f123e663c9e0f3, []int{1}
}

func (m *Tensor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tensor.Unmarshal(m, b)
}
func (m *Tensor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tensor.Marshal(b, m, deterministic)
}
func (m *Tensor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tensor.Merge(m, src)
}
func (m *Tensor) XXX_Size() int {
	return xxx_messageInfo_Tensor.Size(m)
}
func (m *Tensor) XXX_DiscardUnknown() {
	xxx_messageInfo_Tensor.DiscardUnknown(m)
}

var xxx_messageInfo_Tensor proto.InternalMessageInfo

func (m *Tensor) GetType() ValueType {
	if m != nil {
		return m.Type
	}
	return ValueType_UNKNOWN
}

func (m *Tensor) GetShape() *Shape {
	if m != nil {
		return m.Shape
	}
	return nil
}

func (m *Tensor) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ModelMeta struct {
	ID                   string    `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	InputShape           []*Shape  `protobuf:"bytes,2,rep,name=InputShape,proto3" json:"InputShape,omitempty"`
	OutputShape          []*Shape  `protobuf:"bytes,3,rep,name=OutputShape,proto3" json:"OutputShape,omitempty"`
	Path                 string    `protobuf:"bytes,4,opt,name=Path,proto3" json:"Path,omitempty"`
	Type                 ValueType `protobuf:"varint,5,opt,name=Type,proto3,enum=selachii.ValueType" json:"Type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ModelMeta) Reset()         { *m = ModelMeta{} }
func (m *ModelMeta) String() string { return proto.CompactTextString(m) }
func (*ModelMeta) ProtoMessage()    {}
func (*ModelMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_32f123e663c9e0f3, []int{2}
}

func (m *ModelMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModelMeta.Unmarshal(m, b)
}
func (m *ModelMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModelMeta.Marshal(b, m, deterministic)
}
func (m *ModelMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModelMeta.Merge(m, src)
}
func (m *ModelMeta) XXX_Size() int {
	return xxx_messageInfo_ModelMeta.Size(m)
}
func (m *ModelMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_ModelMeta.DiscardUnknown(m)
}

var xxx_messageInfo_ModelMeta proto.InternalMessageInfo

func (m *ModelMeta) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *ModelMeta) GetInputShape() []*Shape {
	if m != nil {
		return m.InputShape
	}
	return nil
}

func (m *ModelMeta) GetOutputShape() []*Shape {
	if m != nil {
		return m.OutputShape
	}
	return nil
}

func (m *ModelMeta) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *ModelMeta) GetType() ValueType {
	if m != nil {
		return m.Type
	}
	return ValueType_UNKNOWN
}

type LoadRequest struct {
	Model                *ModelMeta `protobuf:"bytes,1,opt,name=Model,proto3" json:"Model,omitempty"`
	LoadID               string     `protobuf:"bytes,2,opt,name=LoadID,proto3" json:"LoadID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *LoadRequest) Reset()         { *m = LoadRequest{} }
func (m *LoadRequest) String() string { return proto.CompactTextString(m) }
func (*LoadRequest) ProtoMessage()    {}
func (*LoadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_32f123e663c9e0f3, []int{3}
}

func (m *LoadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadRequest.Unmarshal(m, b)
}
func (m *LoadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadRequest.Marshal(b, m, deterministic)
}
func (m *LoadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadRequest.Merge(m, src)
}
func (m *LoadRequest) XXX_Size() int {
	return xxx_messageInfo_LoadRequest.Size(m)
}
func (m *LoadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoadRequest proto.InternalMessageInfo

func (m *LoadRequest) GetModel() *ModelMeta {
	if m != nil {
		return m.Model
	}
	return nil
}

func (m *LoadRequest) GetLoadID() string {
	if m != nil {
		return m.LoadID
	}
	return ""
}

type UnloadRequest struct {
	LoadID               string   `protobuf:"bytes,1,opt,name=LoadID,proto3" json:"LoadID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnloadRequest) Reset()         { *m = UnloadRequest{} }
func (m *UnloadRequest) String() string { return proto.CompactTextString(m) }
func (*UnloadRequest) ProtoMessage()    {}
func (*UnloadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_32f123e663c9e0f3, []int{4}
}

func (m *UnloadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnloadRequest.Unmarshal(m, b)
}
func (m *UnloadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnloadRequest.Marshal(b, m, deterministic)
}
func (m *UnloadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnloadRequest.Merge(m, src)
}
func (m *UnloadRequest) XXX_Size() int {
	return xxx_messageInfo_UnloadRequest.Size(m)
}
func (m *UnloadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnloadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnloadRequest proto.InternalMessageInfo

func (m *UnloadRequest) GetLoadID() string {
	if m != nil {
		return m.LoadID
	}
	return ""
}

type LoadResponse struct {
	LoadID               string   `protobuf:"bytes,1,opt,name=LoadID,proto3" json:"LoadID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadResponse) Reset()         { *m = LoadResponse{} }
func (m *LoadResponse) String() string { return proto.CompactTextString(m) }
func (*LoadResponse) ProtoMessage()    {}
func (*LoadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_32f123e663c9e0f3, []int{5}
}

func (m *LoadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadResponse.Unmarshal(m, b)
}
func (m *LoadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadResponse.Marshal(b, m, deterministic)
}
func (m *LoadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadResponse.Merge(m, src)
}
func (m *LoadResponse) XXX_Size() int {
	return xxx_messageInfo_LoadResponse.Size(m)
}
func (m *LoadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoadResponse proto.InternalMessageInfo

func (m *LoadResponse) GetLoadID() string {
	if m != nil {
		return m.LoadID
	}
	return ""
}

type UnloadResponse struct {
	DidChange            bool     `protobuf:"varint,1,opt,name=DidChange,proto3" json:"DidChange,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnloadResponse) Reset()         { *m = UnloadResponse{} }
func (m *UnloadResponse) String() string { return proto.CompactTextString(m) }
func (*UnloadResponse) ProtoMessage()    {}
func (*UnloadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_32f123e663c9e0f3, []int{6}
}

func (m *UnloadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnloadResponse.Unmarshal(m, b)
}
func (m *UnloadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnloadResponse.Marshal(b, m, deterministic)
}
func (m *UnloadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnloadResponse.Merge(m, src)
}
func (m *UnloadResponse) XXX_Size() int {
	return xxx_messageInfo_UnloadResponse.Size(m)
}
func (m *UnloadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnloadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnloadResponse proto.InternalMessageInfo

func (m *UnloadResponse) GetDidChange() bool {
	if m != nil {
		return m.DidChange
	}
	return false
}

type RunRequest struct {
	LoadID               string    `protobuf:"bytes,1,opt,name=LoadID,proto3" json:"LoadID,omitempty"`
	Tensor               []*Tensor `protobuf:"bytes,2,rep,name=Tensor,proto3" json:"Tensor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RunRequest) Reset()         { *m = RunRequest{} }
func (m *RunRequest) String() string { return proto.CompactTextString(m) }
func (*RunRequest) ProtoMessage()    {}
func (*RunRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_32f123e663c9e0f3, []int{7}
}

func (m *RunRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunRequest.Unmarshal(m, b)
}
func (m *RunRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunRequest.Marshal(b, m, deterministic)
}
func (m *RunRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunRequest.Merge(m, src)
}
func (m *RunRequest) XXX_Size() int {
	return xxx_messageInfo_RunRequest.Size(m)
}
func (m *RunRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RunRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RunRequest proto.InternalMessageInfo

func (m *RunRequest) GetLoadID() string {
	if m != nil {
		return m.LoadID
	}
	return ""
}

func (m *RunRequest) GetTensor() []*Tensor {
	if m != nil {
		return m.Tensor
	}
	return nil
}

type RunResponse struct {
	Tensor               []*Tensor `protobuf:"bytes,1,rep,name=Tensor,proto3" json:"Tensor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RunResponse) Reset()         { *m = RunResponse{} }
func (m *RunResponse) String() string { return proto.CompactTextString(m) }
func (*RunResponse) ProtoMessage()    {}
func (*RunResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_32f123e663c9e0f3, []int{8}
}

func (m *RunResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunResponse.Unmarshal(m, b)
}
func (m *RunResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunResponse.Marshal(b, m, deterministic)
}
func (m *RunResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunResponse.Merge(m, src)
}
func (m *RunResponse) XXX_Size() int {
	return xxx_messageInfo_RunResponse.Size(m)
}
func (m *RunResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RunResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RunResponse proto.InternalMessageInfo

func (m *RunResponse) GetTensor() []*Tensor {
	if m != nil {
		return m.Tensor
	}
	return nil
}

func init() {
	proto.RegisterEnum("selachii.ValueType", ValueType_name, ValueType_value)
	proto.RegisterType((*Shape)(nil), "selachii.Shape")
	proto.RegisterType((*Tensor)(nil), "selachii.Tensor")
	proto.RegisterType((*ModelMeta)(nil), "selachii.ModelMeta")
	proto.RegisterType((*LoadRequest)(nil), "selachii.LoadRequest")
	proto.RegisterType((*UnloadRequest)(nil), "selachii.UnloadRequest")
	proto.RegisterType((*LoadResponse)(nil), "selachii.LoadResponse")
	proto.RegisterType((*UnloadResponse)(nil), "selachii.UnloadResponse")
	proto.RegisterType((*RunRequest)(nil), "selachii.RunRequest")
	proto.RegisterType((*RunResponse)(nil), "selachii.RunResponse")
}

func init() { proto.RegisterFile("selachii.proto", fileDescriptor_32f123e663c9e0f3) }

var fileDescriptor_32f123e663c9e0f3 = []byte{
	// 511 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xed, 0xc6, 0x71, 0x1a, 0x8f, 0x93, 0xb0, 0x1a, 0xda, 0x12, 0x45, 0x20, 0x45, 0x96, 0xa0,
	0x81, 0x43, 0x50, 0x1c, 0xcb, 0xf4, 0xc0, 0x05, 0x6a, 0x90, 0x2c, 0x12, 0x27, 0xda, 0x26, 0xc0,
	0xd5, 0x10, 0x8b, 0x44, 0xb2, 0x6c, 0x53, 0xdb, 0x07, 0xfe, 0x19, 0x07, 0x4e, 0xfc, 0x32, 0xe4,
	0xdd, 0xf5, 0x47, 0x4b, 0xa1, 0xb7, 0xf9, 0x78, 0xef, 0x8d, 0xdf, 0xcc, 0xca, 0x30, 0x48, 0x83,
	0xd0, 0xff, 0xba, 0x3f, 0x1c, 0xa6, 0xc9, 0x75, 0x9c, 0xc5, 0xd8, 0x2d, 0x73, 0xe3, 0x09, 0xa8,
	0x57, 0x7b, 0x3f, 0x09, 0xf0, 0x04, 0xd4, 0x8f, 0x7e, 0x98, 0x07, 0x43, 0x32, 0x56, 0x26, 0x0a,
	0x13, 0x89, 0x11, 0x42, 0x67, 0x13, 0x44, 0x69, 0x7c, 0x8d, 0xe7, 0xd0, 0xde, 0xfc, 0x48, 0x8a,
	0x36, 0x99, 0x0c, 0xcc, 0x87, 0xd3, 0x4a, 0x91, 0x03, 0x8b, 0x16, 0xe3, 0x00, 0x7c, 0x2a, 0x15,
	0x87, 0xad, 0x31, 0x99, 0xe8, 0xe6, 0x83, 0x1a, 0xc9, 0xcb, 0x4c, 0xce, 0x43, 0x68, 0x3b, 0x7e,
	0xe6, 0x0f, 0x95, 0x31, 0x99, 0xf4, 0x18, 0x8f, 0x8d, 0x5f, 0x04, 0xb4, 0x65, 0xbc, 0x0b, 0xc2,
	0x65, 0x90, 0xf9, 0x38, 0x80, 0x96, 0xeb, 0xf0, 0x79, 0x1a, 0x6b, 0xb9, 0x0e, 0xbe, 0x04, 0x70,
	0xa3, 0x24, 0xcf, 0x4a, 0x75, 0xe5, 0x2e, 0xf5, 0x06, 0x04, 0x67, 0xa0, 0xaf, 0xf2, 0xac, 0x62,
	0x28, 0x77, 0x33, 0x9a, 0x98, 0xe2, 0xab, 0xd6, 0x7e, 0xb6, 0x1f, 0xb6, 0xf9, 0x54, 0x1e, 0x57,
	0xce, 0xd5, 0x7b, 0x9c, 0x1b, 0x6b, 0xd0, 0x17, 0xb1, 0xbf, 0x63, 0xc1, 0xf7, 0x3c, 0x48, 0x33,
	0x7c, 0x0e, 0x2a, 0x37, 0xc3, 0x2d, 0xe8, 0x4d, 0x62, 0xe5, 0x91, 0x09, 0x04, 0x9e, 0x41, 0xa7,
	0x60, 0xba, 0x0e, 0x5f, 0x9a, 0xc6, 0x64, 0x66, 0x9c, 0x43, 0x7f, 0x1b, 0x85, 0x0d, 0xcd, 0x1a,
	0x48, 0x6e, 0x00, 0x9f, 0x41, 0x4f, 0x8c, 0x4e, 0x93, 0x38, 0x4a, 0x83, 0x7f, 0xe2, 0xa6, 0x30,
	0x28, 0x05, 0x25, 0xf2, 0x31, 0x68, 0xce, 0x61, 0x77, 0xb9, 0xf7, 0xa3, 0x6f, 0xe2, 0xb8, 0x5d,
	0x56, 0x17, 0x0c, 0x0f, 0x80, 0xe5, 0xd1, 0x3d, 0xd3, 0x71, 0x52, 0xbe, 0x12, 0x79, 0x15, 0x5a,
	0x5b, 0x15, 0x75, 0x26, 0xfb, 0xc6, 0x2b, 0xd0, 0xb9, 0x9e, 0x1c, 0x5e, 0x13, 0xc9, 0xff, 0x89,
	0x2f, 0x7e, 0x12, 0xd0, 0xaa, 0x7d, 0xa3, 0x0e, 0xc7, 0x5b, 0xef, 0x83, 0xb7, 0xfa, 0xe4, 0xd1,
	0xa3, 0x22, 0x79, 0xbf, 0x58, 0xbd, 0xd9, 0xcc, 0x6c, 0x4a, 0xaa, 0x64, 0x6e, 0xd2, 0x56, 0x95,
	0xd8, 0x16, 0x55, 0x50, 0x03, 0x75, 0xeb, 0x7a, 0x9b, 0x0b, 0xda, 0x46, 0x80, 0x4e, 0x11, 0xce,
	0x6c, 0xaa, 0x96, 0xf1, 0xdc, 0xa4, 0x9d, 0x32, 0xb6, 0x2d, 0x7a, 0x8c, 0x5d, 0x68, 0x73, 0x74,
	0xb7, 0x20, 0x0a, 0xb0, 0x26, 0xc3, 0xb9, 0x49, 0x41, 0x86, 0xb6, 0x45, 0x75, 0xec, 0x83, 0x76,
	0xb9, 0x5a, 0xae, 0x17, 0xef, 0x3e, 0xdb, 0x16, 0xed, 0xe1, 0x00, 0x40, 0xa6, 0x33, 0xf3, 0x82,
	0xf6, 0xcd, 0xdf, 0x04, 0xba, 0x57, 0xd2, 0x16, 0xbe, 0x06, 0xad, 0x58, 0x9a, 0x38, 0xfb, 0x69,
	0x6d, 0xb7, 0xf1, 0x70, 0x46, 0x67, 0xb7, 0xcb, 0x62, 0x5b, 0xc6, 0x11, 0xbe, 0x05, 0x5d, 0x9c,
	0x4f, 0xf0, 0x1f, 0xd5, 0xc0, 0x1b, 0xcf, 0x64, 0x34, 0xfc, 0xbb, 0x51, 0x69, 0x58, 0xa0, 0xb0,
	0x3c, 0xc2, 0x93, 0x1a, 0x52, 0x5f, 0x78, 0x74, 0x7a, 0xab, 0x5a, 0xb2, 0xbe, 0x74, 0xf8, 0x8f,
	0x63, 0xfe, 0x27, 0x00, 0x00, 0xff, 0xff, 0x69, 0x82, 0x8e, 0x87, 0x4a, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SelachiiClient is the client API for Selachii service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SelachiiClient interface {
	LoadModel(ctx context.Context, in *LoadRequest, opts ...grpc.CallOption) (*LoadResponse, error)
	UnloadModel(ctx context.Context, in *UnloadRequest, opts ...grpc.CallOption) (*UnloadResponse, error)
	Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error)
}

type selachiiClient struct {
	cc *grpc.ClientConn
}

func NewSelachiiClient(cc *grpc.ClientConn) SelachiiClient {
	return &selachiiClient{cc}
}

func (c *selachiiClient) LoadModel(ctx context.Context, in *LoadRequest, opts ...grpc.CallOption) (*LoadResponse, error) {
	out := new(LoadResponse)
	err := c.cc.Invoke(ctx, "/selachii.Selachii/LoadModel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *selachiiClient) UnloadModel(ctx context.Context, in *UnloadRequest, opts ...grpc.CallOption) (*UnloadResponse, error) {
	out := new(UnloadResponse)
	err := c.cc.Invoke(ctx, "/selachii.Selachii/UnloadModel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *selachiiClient) Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error) {
	out := new(RunResponse)
	err := c.cc.Invoke(ctx, "/selachii.Selachii/Run", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SelachiiServer is the server API for Selachii service.
type SelachiiServer interface {
	LoadModel(context.Context, *LoadRequest) (*LoadResponse, error)
	UnloadModel(context.Context, *UnloadRequest) (*UnloadResponse, error)
	Run(context.Context, *RunRequest) (*RunResponse, error)
}

// UnimplementedSelachiiServer can be embedded to have forward compatible implementations.
type UnimplementedSelachiiServer struct {
}

func (*UnimplementedSelachiiServer) LoadModel(ctx context.Context, req *LoadRequest) (*LoadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadModel not implemented")
}
func (*UnimplementedSelachiiServer) UnloadModel(ctx context.Context, req *UnloadRequest) (*UnloadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnloadModel not implemented")
}
func (*UnimplementedSelachiiServer) Run(ctx context.Context, req *RunRequest) (*RunResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Run not implemented")
}

func RegisterSelachiiServer(s *grpc.Server, srv SelachiiServer) {
	s.RegisterService(&_Selachii_serviceDesc, srv)
}

func _Selachii_LoadModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SelachiiServer).LoadModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/selachii.Selachii/LoadModel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SelachiiServer).LoadModel(ctx, req.(*LoadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Selachii_UnloadModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SelachiiServer).UnloadModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/selachii.Selachii/UnloadModel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SelachiiServer).UnloadModel(ctx, req.(*UnloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Selachii_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SelachiiServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/selachii.Selachii/Run",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SelachiiServer).Run(ctx, req.(*RunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Selachii_serviceDesc = grpc.ServiceDesc{
	ServiceName: "selachii.Selachii",
	HandlerType: (*SelachiiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoadModel",
			Handler:    _Selachii_LoadModel_Handler,
		},
		{
			MethodName: "UnloadModel",
			Handler:    _Selachii_UnloadModel_Handler,
		},
		{
			MethodName: "Run",
			Handler:    _Selachii_Run_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "selachii.proto",
}
