// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ardea.proto

package ardea

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ValueType int32

const (
	ValueType_UNKNOWN    ValueType = 0
	ValueType_FLOAT16    ValueType = 1
	ValueType_FLOAT32    ValueType = 2
	ValueType_FLOAT64    ValueType = 3
	ValueType_UINT8      ValueType = 4
	ValueType_UINT16     ValueType = 5
	ValueType_UINT32     ValueType = 6
	ValueType_UINT64     ValueType = 7
	ValueType_INT8       ValueType = 8
	ValueType_INT16      ValueType = 9
	ValueType_INT32      ValueType = 10
	ValueType_INT64      ValueType = 11
	ValueType_COMPLEX64  ValueType = 12
	ValueType_COMPLEX128 ValueType = 13
)

var ValueType_name = map[int32]string{
	0:  "UNKNOWN",
	1:  "FLOAT16",
	2:  "FLOAT32",
	3:  "FLOAT64",
	4:  "UINT8",
	5:  "UINT16",
	6:  "UINT32",
	7:  "UINT64",
	8:  "INT8",
	9:  "INT16",
	10: "INT32",
	11: "INT64",
	12: "COMPLEX64",
	13: "COMPLEX128",
}

var ValueType_value = map[string]int32{
	"UNKNOWN":    0,
	"FLOAT16":    1,
	"FLOAT32":    2,
	"FLOAT64":    3,
	"UINT8":      4,
	"UINT16":     5,
	"UINT32":     6,
	"UINT64":     7,
	"INT8":       8,
	"INT16":      9,
	"INT32":      10,
	"INT64":      11,
	"COMPLEX64":  12,
	"COMPLEX128": 13,
}

func (x ValueType) String() string {
	return proto.EnumName(ValueType_name, int32(x))
}

func (ValueType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7d743a17b43fe552, []int{0}
}

type ModelState int32

const (
	ModelState_STATE_UNKNOWN    ModelState = 0
	ModelState_STATE_INIT       ModelState = 1
	ModelState_STATE_PROCESSING ModelState = 2
	ModelState_STATE_READY      ModelState = 3
	ModelState_STATE_INVALID    ModelState = 4
	ModelState_STATE_DELETED    ModelState = 5
)

var ModelState_name = map[int32]string{
	0: "STATE_UNKNOWN",
	1: "STATE_INIT",
	2: "STATE_PROCESSING",
	3: "STATE_READY",
	4: "STATE_INVALID",
	5: "STATE_DELETED",
}

var ModelState_value = map[string]int32{
	"STATE_UNKNOWN":    0,
	"STATE_INIT":       1,
	"STATE_PROCESSING": 2,
	"STATE_READY":      3,
	"STATE_INVALID":    4,
	"STATE_DELETED":    5,
}

func (x ModelState) String() string {
	return proto.EnumName(ModelState_name, int32(x))
}

func (ModelState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7d743a17b43fe552, []int{1}
}

type NullInt64 struct {
	Value                int64    `protobuf:"varint,1,opt,name=Value,proto3" json:"Value,omitempty"`
	IsValid              bool     `protobuf:"varint,2,opt,name=IsValid,proto3" json:"IsValid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NullInt64) Reset()         { *m = NullInt64{} }
func (m *NullInt64) String() string { return proto.CompactTextString(m) }
func (*NullInt64) ProtoMessage()    {}
func (*NullInt64) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d743a17b43fe552, []int{0}
}

func (m *NullInt64) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NullInt64.Unmarshal(m, b)
}
func (m *NullInt64) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NullInt64.Marshal(b, m, deterministic)
}
func (m *NullInt64) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NullInt64.Merge(m, src)
}
func (m *NullInt64) XXX_Size() int {
	return xxx_messageInfo_NullInt64.Size(m)
}
func (m *NullInt64) XXX_DiscardUnknown() {
	xxx_messageInfo_NullInt64.DiscardUnknown(m)
}

var xxx_messageInfo_NullInt64 proto.InternalMessageInfo

func (m *NullInt64) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *NullInt64) GetIsValid() bool {
	if m != nil {
		return m.IsValid
	}
	return false
}

type Shape struct {
	Value                []*NullInt64 `protobuf:"bytes,1,rep,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Shape) Reset()         { *m = Shape{} }
func (m *Shape) String() string { return proto.CompactTextString(m) }
func (*Shape) ProtoMessage()    {}
func (*Shape) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d743a17b43fe552, []int{1}
}

func (m *Shape) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Shape.Unmarshal(m, b)
}
func (m *Shape) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Shape.Marshal(b, m, deterministic)
}
func (m *Shape) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Shape.Merge(m, src)
}
func (m *Shape) XXX_Size() int {
	return xxx_messageInfo_Shape.Size(m)
}
func (m *Shape) XXX_DiscardUnknown() {
	xxx_messageInfo_Shape.DiscardUnknown(m)
}

var xxx_messageInfo_Shape proto.InternalMessageInfo

func (m *Shape) GetValue() []*NullInt64 {
	if m != nil {
		return m.Value
	}
	return nil
}

type Model struct {
	ID                   string     `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	OwnerID              string     `protobuf:"bytes,2,opt,name=OwnerID,proto3" json:"OwnerID,omitempty"`
	State                ModelState `protobuf:"varint,3,opt,name=State,proto3,enum=ardea.ModelState" json:"State,omitempty"`
	InputShape           []*Shape   `protobuf:"bytes,4,rep,name=InputShape,proto3" json:"InputShape,omitempty"`
	OutputShape          []*Shape   `protobuf:"bytes,5,rep,name=OutputShape,proto3" json:"OutputShape,omitempty"`
	Path                 string     `protobuf:"bytes,6,opt,name=Path,proto3" json:"Path,omitempty"`
	Name                 string     `protobuf:"bytes,7,opt,name=Name,proto3" json:"Name,omitempty"`
	Type                 ValueType  `protobuf:"varint,8,opt,name=Type,proto3,enum=ardea.ValueType" json:"Type,omitempty"`
	ErrStrSet            bool       `protobuf:"varint,9,opt,name=ErrStrSet,proto3" json:"ErrStrSet,omitempty"`
	ErrStr               string     `protobuf:"bytes,10,opt,name=ErrStr,proto3" json:"ErrStr,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Model) Reset()         { *m = Model{} }
func (m *Model) String() string { return proto.CompactTextString(m) }
func (*Model) ProtoMessage()    {}
func (*Model) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d743a17b43fe552, []int{2}
}

func (m *Model) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Model.Unmarshal(m, b)
}
func (m *Model) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Model.Marshal(b, m, deterministic)
}
func (m *Model) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Model.Merge(m, src)
}
func (m *Model) XXX_Size() int {
	return xxx_messageInfo_Model.Size(m)
}
func (m *Model) XXX_DiscardUnknown() {
	xxx_messageInfo_Model.DiscardUnknown(m)
}

var xxx_messageInfo_Model proto.InternalMessageInfo

func (m *Model) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Model) GetOwnerID() string {
	if m != nil {
		return m.OwnerID
	}
	return ""
}

func (m *Model) GetState() ModelState {
	if m != nil {
		return m.State
	}
	return ModelState_STATE_UNKNOWN
}

func (m *Model) GetInputShape() []*Shape {
	if m != nil {
		return m.InputShape
	}
	return nil
}

func (m *Model) GetOutputShape() []*Shape {
	if m != nil {
		return m.OutputShape
	}
	return nil
}

func (m *Model) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Model) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Model) GetType() ValueType {
	if m != nil {
		return m.Type
	}
	return ValueType_UNKNOWN
}

func (m *Model) GetErrStrSet() bool {
	if m != nil {
		return m.ErrStrSet
	}
	return false
}

func (m *Model) GetErrStr() string {
	if m != nil {
		return m.ErrStr
	}
	return ""
}

type CreateModelRequest struct {
	OwnerID              string    `protobuf:"bytes,1,opt,name=OwnerID,proto3" json:"OwnerID,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	InputShape           []*Shape  `protobuf:"bytes,3,rep,name=InputShape,proto3" json:"InputShape,omitempty"`
	OutputShape          []*Shape  `protobuf:"bytes,4,rep,name=OutputShape,proto3" json:"OutputShape,omitempty"`
	Type                 ValueType `protobuf:"varint,5,opt,name=Type,proto3,enum=ardea.ValueType" json:"Type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateModelRequest) Reset()         { *m = CreateModelRequest{} }
func (m *CreateModelRequest) String() string { return proto.CompactTextString(m) }
func (*CreateModelRequest) ProtoMessage()    {}
func (*CreateModelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d743a17b43fe552, []int{3}
}

func (m *CreateModelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateModelRequest.Unmarshal(m, b)
}
func (m *CreateModelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateModelRequest.Marshal(b, m, deterministic)
}
func (m *CreateModelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateModelRequest.Merge(m, src)
}
func (m *CreateModelRequest) XXX_Size() int {
	return xxx_messageInfo_CreateModelRequest.Size(m)
}
func (m *CreateModelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateModelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateModelRequest proto.InternalMessageInfo

func (m *CreateModelRequest) GetOwnerID() string {
	if m != nil {
		return m.OwnerID
	}
	return ""
}

func (m *CreateModelRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateModelRequest) GetInputShape() []*Shape {
	if m != nil {
		return m.InputShape
	}
	return nil
}

func (m *CreateModelRequest) GetOutputShape() []*Shape {
	if m != nil {
		return m.OutputShape
	}
	return nil
}

func (m *CreateModelRequest) GetType() ValueType {
	if m != nil {
		return m.Type
	}
	return ValueType_UNKNOWN
}

type CreateModelReply struct {
	Model                *Model   `protobuf:"bytes,1,opt,name=Model,proto3" json:"Model,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateModelReply) Reset()         { *m = CreateModelReply{} }
func (m *CreateModelReply) String() string { return proto.CompactTextString(m) }
func (*CreateModelReply) ProtoMessage()    {}
func (*CreateModelReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d743a17b43fe552, []int{4}
}

func (m *CreateModelReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateModelReply.Unmarshal(m, b)
}
func (m *CreateModelReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateModelReply.Marshal(b, m, deterministic)
}
func (m *CreateModelReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateModelReply.Merge(m, src)
}
func (m *CreateModelReply) XXX_Size() int {
	return xxx_messageInfo_CreateModelReply.Size(m)
}
func (m *CreateModelReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateModelReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateModelReply proto.InternalMessageInfo

func (m *CreateModelReply) GetModel() *Model {
	if m != nil {
		return m.Model
	}
	return nil
}

type GetModelRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetModelRequest) Reset()         { *m = GetModelRequest{} }
func (m *GetModelRequest) String() string { return proto.CompactTextString(m) }
func (*GetModelRequest) ProtoMessage()    {}
func (*GetModelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d743a17b43fe552, []int{5}
}

func (m *GetModelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetModelRequest.Unmarshal(m, b)
}
func (m *GetModelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetModelRequest.Marshal(b, m, deterministic)
}
func (m *GetModelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetModelRequest.Merge(m, src)
}
func (m *GetModelRequest) XXX_Size() int {
	return xxx_messageInfo_GetModelRequest.Size(m)
}
func (m *GetModelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetModelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetModelRequest proto.InternalMessageInfo

func (m *GetModelRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type GetModelByNameRequest struct {
	OwnerID              string   `protobuf:"bytes,1,opt,name=OwnerID,proto3" json:"OwnerID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetModelByNameRequest) Reset()         { *m = GetModelByNameRequest{} }
func (m *GetModelByNameRequest) String() string { return proto.CompactTextString(m) }
func (*GetModelByNameRequest) ProtoMessage()    {}
func (*GetModelByNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d743a17b43fe552, []int{6}
}

func (m *GetModelByNameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetModelByNameRequest.Unmarshal(m, b)
}
func (m *GetModelByNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetModelByNameRequest.Marshal(b, m, deterministic)
}
func (m *GetModelByNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetModelByNameRequest.Merge(m, src)
}
func (m *GetModelByNameRequest) XXX_Size() int {
	return xxx_messageInfo_GetModelByNameRequest.Size(m)
}
func (m *GetModelByNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetModelByNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetModelByNameRequest proto.InternalMessageInfo

func (m *GetModelByNameRequest) GetOwnerID() string {
	if m != nil {
		return m.OwnerID
	}
	return ""
}

func (m *GetModelByNameRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetModelReply struct {
	Model                *Model   `protobuf:"bytes,1,opt,name=Model,proto3" json:"Model,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetModelReply) Reset()         { *m = GetModelReply{} }
func (m *GetModelReply) String() string { return proto.CompactTextString(m) }
func (*GetModelReply) ProtoMessage()    {}
func (*GetModelReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d743a17b43fe552, []int{7}
}

func (m *GetModelReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetModelReply.Unmarshal(m, b)
}
func (m *GetModelReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetModelReply.Marshal(b, m, deterministic)
}
func (m *GetModelReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetModelReply.Merge(m, src)
}
func (m *GetModelReply) XXX_Size() int {
	return xxx_messageInfo_GetModelReply.Size(m)
}
func (m *GetModelReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetModelReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetModelReply proto.InternalMessageInfo

func (m *GetModelReply) GetModel() *Model {
	if m != nil {
		return m.Model
	}
	return nil
}

type UpdateModelStateRequest struct {
	ID                   string     `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	State                ModelState `protobuf:"varint,2,opt,name=State,proto3,enum=ardea.ModelState" json:"State,omitempty"`
	ErrStrSet            bool       `protobuf:"varint,3,opt,name=ErrStrSet,proto3" json:"ErrStrSet,omitempty"`
	ErrStr               string     `protobuf:"bytes,4,opt,name=ErrStr,proto3" json:"ErrStr,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UpdateModelStateRequest) Reset()         { *m = UpdateModelStateRequest{} }
func (m *UpdateModelStateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateModelStateRequest) ProtoMessage()    {}
func (*UpdateModelStateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d743a17b43fe552, []int{8}
}

func (m *UpdateModelStateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateModelStateRequest.Unmarshal(m, b)
}
func (m *UpdateModelStateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateModelStateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateModelStateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateModelStateRequest.Merge(m, src)
}
func (m *UpdateModelStateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateModelStateRequest.Size(m)
}
func (m *UpdateModelStateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateModelStateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateModelStateRequest proto.InternalMessageInfo

func (m *UpdateModelStateRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *UpdateModelStateRequest) GetState() ModelState {
	if m != nil {
		return m.State
	}
	return ModelState_STATE_UNKNOWN
}

func (m *UpdateModelStateRequest) GetErrStrSet() bool {
	if m != nil {
		return m.ErrStrSet
	}
	return false
}

func (m *UpdateModelStateRequest) GetErrStr() string {
	if m != nil {
		return m.ErrStr
	}
	return ""
}

type UpdateModelStateReply struct {
	Model                *Model   `protobuf:"bytes,1,opt,name=Model,proto3" json:"Model,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateModelStateReply) Reset()         { *m = UpdateModelStateReply{} }
func (m *UpdateModelStateReply) String() string { return proto.CompactTextString(m) }
func (*UpdateModelStateReply) ProtoMessage()    {}
func (*UpdateModelStateReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d743a17b43fe552, []int{9}
}

func (m *UpdateModelStateReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateModelStateReply.Unmarshal(m, b)
}
func (m *UpdateModelStateReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateModelStateReply.Marshal(b, m, deterministic)
}
func (m *UpdateModelStateReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateModelStateReply.Merge(m, src)
}
func (m *UpdateModelStateReply) XXX_Size() int {
	return xxx_messageInfo_UpdateModelStateReply.Size(m)
}
func (m *UpdateModelStateReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateModelStateReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateModelStateReply proto.InternalMessageInfo

func (m *UpdateModelStateReply) GetModel() *Model {
	if m != nil {
		return m.Model
	}
	return nil
}

type UpdateModelPathRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=Path,proto3" json:"Path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateModelPathRequest) Reset()         { *m = UpdateModelPathRequest{} }
func (m *UpdateModelPathRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateModelPathRequest) ProtoMessage()    {}
func (*UpdateModelPathRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d743a17b43fe552, []int{10}
}

func (m *UpdateModelPathRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateModelPathRequest.Unmarshal(m, b)
}
func (m *UpdateModelPathRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateModelPathRequest.Marshal(b, m, deterministic)
}
func (m *UpdateModelPathRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateModelPathRequest.Merge(m, src)
}
func (m *UpdateModelPathRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateModelPathRequest.Size(m)
}
func (m *UpdateModelPathRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateModelPathRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateModelPathRequest proto.InternalMessageInfo

func (m *UpdateModelPathRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *UpdateModelPathRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type ListModelsRequest struct {
	OwnerID              string   `protobuf:"bytes,1,opt,name=OwnerID,proto3" json:"OwnerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListModelsRequest) Reset()         { *m = ListModelsRequest{} }
func (m *ListModelsRequest) String() string { return proto.CompactTextString(m) }
func (*ListModelsRequest) ProtoMessage()    {}
func (*ListModelsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d743a17b43fe552, []int{11}
}

func (m *ListModelsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListModelsRequest.Unmarshal(m, b)
}
func (m *ListModelsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListModelsRequest.Marshal(b, m, deterministic)
}
func (m *ListModelsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListModelsRequest.Merge(m, src)
}
func (m *ListModelsRequest) XXX_Size() int {
	return xxx_messageInfo_ListModelsRequest.Size(m)
}
func (m *ListModelsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListModelsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListModelsRequest proto.InternalMessageInfo

func (m *ListModelsRequest) GetOwnerID() string {
	if m != nil {
		return m.OwnerID
	}
	return ""
}

type ListModelsReply struct {
	Models               []*Model `protobuf:"bytes,1,rep,name=Models,proto3" json:"Models,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListModelsReply) Reset()         { *m = ListModelsReply{} }
func (m *ListModelsReply) String() string { return proto.CompactTextString(m) }
func (*ListModelsReply) ProtoMessage()    {}
func (*ListModelsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d743a17b43fe552, []int{12}
}

func (m *ListModelsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListModelsReply.Unmarshal(m, b)
}
func (m *ListModelsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListModelsReply.Marshal(b, m, deterministic)
}
func (m *ListModelsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListModelsReply.Merge(m, src)
}
func (m *ListModelsReply) XXX_Size() int {
	return xxx_messageInfo_ListModelsReply.Size(m)
}
func (m *ListModelsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListModelsReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListModelsReply proto.InternalMessageInfo

func (m *ListModelsReply) GetModels() []*Model {
	if m != nil {
		return m.Models
	}
	return nil
}

type UpdateModelPathReply struct {
	Model                *Model   `protobuf:"bytes,1,opt,name=Model,proto3" json:"Model,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateModelPathReply) Reset()         { *m = UpdateModelPathReply{} }
func (m *UpdateModelPathReply) String() string { return proto.CompactTextString(m) }
func (*UpdateModelPathReply) ProtoMessage()    {}
func (*UpdateModelPathReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d743a17b43fe552, []int{13}
}

func (m *UpdateModelPathReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateModelPathReply.Unmarshal(m, b)
}
func (m *UpdateModelPathReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateModelPathReply.Marshal(b, m, deterministic)
}
func (m *UpdateModelPathReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateModelPathReply.Merge(m, src)
}
func (m *UpdateModelPathReply) XXX_Size() int {
	return xxx_messageInfo_UpdateModelPathReply.Size(m)
}
func (m *UpdateModelPathReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateModelPathReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateModelPathReply proto.InternalMessageInfo

func (m *UpdateModelPathReply) GetModel() *Model {
	if m != nil {
		return m.Model
	}
	return nil
}

func init() {
	proto.RegisterEnum("ardea.ValueType", ValueType_name, ValueType_value)
	proto.RegisterEnum("ardea.ModelState", ModelState_name, ModelState_value)
	proto.RegisterType((*NullInt64)(nil), "ardea.NullInt64")
	proto.RegisterType((*Shape)(nil), "ardea.Shape")
	proto.RegisterType((*Model)(nil), "ardea.Model")
	proto.RegisterType((*CreateModelRequest)(nil), "ardea.CreateModelRequest")
	proto.RegisterType((*CreateModelReply)(nil), "ardea.CreateModelReply")
	proto.RegisterType((*GetModelRequest)(nil), "ardea.GetModelRequest")
	proto.RegisterType((*GetModelByNameRequest)(nil), "ardea.GetModelByNameRequest")
	proto.RegisterType((*GetModelReply)(nil), "ardea.GetModelReply")
	proto.RegisterType((*UpdateModelStateRequest)(nil), "ardea.UpdateModelStateRequest")
	proto.RegisterType((*UpdateModelStateReply)(nil), "ardea.UpdateModelStateReply")
	proto.RegisterType((*UpdateModelPathRequest)(nil), "ardea.UpdateModelPathRequest")
	proto.RegisterType((*ListModelsRequest)(nil), "ardea.ListModelsRequest")
	proto.RegisterType((*ListModelsReply)(nil), "ardea.ListModelsReply")
	proto.RegisterType((*UpdateModelPathReply)(nil), "ardea.UpdateModelPathReply")
}

func init() { proto.RegisterFile("ardea.proto", fileDescriptor_7d743a17b43fe552) }

var fileDescriptor_7d743a17b43fe552 = []byte{
	// 761 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0x6d, 0x6f, 0xd2, 0x6c,
	0x14, 0x7e, 0xfa, 0x06, 0xf4, 0x30, 0xe0, 0xde, 0x09, 0x63, 0x7d, 0x78, 0xf6, 0x98, 0xd9, 0x2c,
	0x4a, 0x16, 0x9d, 0x19, 0x90, 0xba, 0x38, 0x63, 0x82, 0x6b, 0x5d, 0x1a, 0x59, 0x21, 0x85, 0x4d,
	0xfd, 0x64, 0x6a, 0x68, 0xb2, 0x25, 0xb8, 0x21, 0x94, 0x18, 0x12, 0x7f, 0x80, 0xff, 0xc5, 0x3f,
	0xe0, 0x07, 0x3f, 0xfb, 0xbb, 0xcc, 0x7d, 0xf7, 0x2e, 0x6d, 0x79, 0x71, 0xd3, 0x6f, 0xe7, 0xe5,
	0xba, 0xcf, 0x39, 0xd7, 0xe1, 0x5c, 0x05, 0xf2, 0xde, 0x78, 0xe0, 0x7b, 0x07, 0xa3, 0xf1, 0x4d,
	0x70, 0x83, 0x0a, 0x73, 0xf4, 0x63, 0x50, 0x9d, 0xe9, 0x70, 0x68, 0x5f, 0x07, 0x46, 0x13, 0xcb,
	0xa0, 0x5c, 0x78, 0xc3, 0xa9, 0xaf, 0x09, 0xbb, 0x42, 0x4d, 0x72, 0x43, 0x07, 0x35, 0xc8, 0xda,
	0x93, 0x0b, 0x6f, 0x78, 0x35, 0xd0, 0xc4, 0x5d, 0xa1, 0x96, 0x73, 0x23, 0x57, 0x7f, 0x02, 0x4a,
	0xef, 0xd2, 0x1b, 0xf9, 0xf8, 0x20, 0x7e, 0x28, 0xd5, 0xf2, 0x75, 0x72, 0x10, 0x76, 0x9a, 0x57,
	0xe6, 0xa5, 0xf4, 0x1f, 0x22, 0x28, 0x67, 0x37, 0x03, 0x7f, 0x88, 0x45, 0x10, 0x6d, 0x93, 0xf5,
	0x51, 0x5d, 0xd1, 0x36, 0x69, 0x93, 0xce, 0xe7, 0x6b, 0x7f, 0x6c, 0x9b, 0xac, 0x89, 0xea, 0x46,
	0x2e, 0x3e, 0x04, 0xa5, 0x17, 0x78, 0x81, 0xaf, 0x49, 0xbb, 0x42, 0xad, 0x58, 0xdf, 0xe4, 0xb5,
	0x59, 0x19, 0x96, 0x70, 0xc3, 0x3c, 0x3e, 0x02, 0xb0, 0xaf, 0x47, 0xd3, 0x80, 0x8d, 0xa4, 0xc9,
	0x6c, 0x92, 0x0d, 0x8e, 0x66, 0x31, 0x37, 0x91, 0xc7, 0x03, 0xc8, 0x77, 0xa6, 0xc1, 0x1c, 0xae,
	0xac, 0x80, 0x27, 0x01, 0x88, 0x20, 0x77, 0xbd, 0xe0, 0x52, 0xcb, 0xb0, 0xe9, 0x98, 0x4d, 0x63,
	0x8e, 0xf7, 0xd1, 0xd7, 0xb2, 0x61, 0x8c, 0xda, 0xb8, 0x07, 0x72, 0x7f, 0x36, 0xf2, 0xb5, 0x1c,
	0x9b, 0x36, 0xda, 0x04, 0xa3, 0x4f, 0xe3, 0x2e, 0xcb, 0xe2, 0x0e, 0xa8, 0xd6, 0x78, 0xdc, 0x0b,
	0xc6, 0x3d, 0x3f, 0xd0, 0x54, 0xb6, 0xd5, 0x38, 0x80, 0x15, 0xc8, 0x84, 0x8e, 0x06, 0xac, 0x32,
	0xf7, 0xf4, 0x9f, 0x02, 0xe0, 0xc9, 0xd8, 0xf7, 0x02, 0x9f, 0xb1, 0x77, 0xfd, 0x4f, 0x53, 0x7f,
	0x12, 0x24, 0x77, 0x27, 0xa4, 0x77, 0x17, 0x0d, 0x28, 0x26, 0x06, 0x4c, 0xaf, 0x49, 0xfa, 0xb3,
	0x35, 0xc9, 0xb7, 0xad, 0x29, 0xa2, 0xaf, 0xfc, 0x8e, 0xbe, 0x6e, 0x00, 0x49, 0xf1, 0x18, 0x0d,
	0x67, 0xa8, 0xf3, 0xd3, 0x60, 0x1c, 0xe2, 0x1e, 0x21, 0x22, 0x4c, 0xe9, 0xf7, 0xa1, 0x74, 0xea,
	0x07, 0x29, 0xf2, 0x0b, 0x87, 0xa4, 0x5b, 0xb0, 0x15, 0x41, 0x5e, 0xce, 0x28, 0xe1, 0xbf, 0xda,
	0x92, 0xde, 0x80, 0x42, 0xdc, 0xe9, 0xae, 0xe3, 0x7d, 0x15, 0x60, 0xfb, 0x7c, 0x34, 0x88, 0x78,
	0x85, 0xd7, 0xb9, 0x7a, 0xce, 0xf8, 0xac, 0xc5, 0x5b, 0xce, 0x3a, 0x75, 0x2a, 0xd2, 0xfa, 0x53,
	0x91, 0x53, 0xa7, 0x72, 0x0c, 0x5b, 0xcb, 0x93, 0xdc, 0x95, 0xc7, 0x73, 0xa8, 0x24, 0x1e, 0xd3,
	0x53, 0x5f, 0xc7, 0x22, 0x52, 0x85, 0x18, 0xab, 0x42, 0x7f, 0x0c, 0x9b, 0xed, 0xab, 0x49, 0xb8,
	0xbb, 0xc9, 0xad, 0xdb, 0xd7, 0x9f, 0x42, 0x29, 0x09, 0xa7, 0x33, 0xee, 0x41, 0x26, 0x74, 0xf9,
	0xf7, 0x24, 0x3d, 0x24, 0xcf, 0xe9, 0xcf, 0xa0, 0xbc, 0x34, 0xe5, 0x1d, 0x19, 0xee, 0x7f, 0x17,
	0x40, 0x9d, 0x1f, 0x25, 0xe6, 0x21, 0x7b, 0xee, 0xbc, 0x76, 0x3a, 0x6f, 0x1c, 0xf2, 0x0f, 0x75,
	0x5e, 0xb5, 0x3b, 0xad, 0xfe, 0xa1, 0x41, 0x84, 0xb9, 0xd3, 0xa8, 0x13, 0x71, 0xee, 0x18, 0x4d,
	0x22, 0xa1, 0x0a, 0xca, 0xb9, 0xed, 0xf4, 0x8f, 0x88, 0x8c, 0x00, 0x19, 0x6a, 0x1e, 0x1a, 0x44,
	0x89, 0xec, 0x46, 0x9d, 0x64, 0x22, 0xdb, 0x68, 0x92, 0x2c, 0xe6, 0x40, 0x66, 0xe8, 0x1c, 0x7d,
	0x18, 0x82, 0x55, 0x6e, 0x36, 0xea, 0x04, 0xb8, 0x69, 0x34, 0x49, 0x1e, 0x0b, 0xa0, 0x9e, 0x74,
	0xce, 0xba, 0x6d, 0xeb, 0xad, 0xd1, 0x24, 0x1b, 0x58, 0x04, 0xe0, 0xee, 0x61, 0xfd, 0x88, 0x14,
	0xf6, 0xbf, 0x00, 0xc4, 0xbf, 0x29, 0x6e, 0x42, 0xa1, 0xd7, 0x6f, 0xf5, 0xad, 0xf7, 0x31, 0x81,
	0x22, 0x40, 0x18, 0xb2, 0x1d, 0xbb, 0x4f, 0x04, 0x2c, 0x03, 0x09, 0xfd, 0xae, 0xdb, 0x39, 0xb1,
	0x7a, 0x3d, 0xdb, 0x39, 0x25, 0x22, 0x96, 0x20, 0x1f, 0x46, 0x5d, 0xab, 0x65, 0xbe, 0x23, 0x52,
	0x5c, 0xc9, 0x76, 0x2e, 0x5a, 0x6d, 0xdb, 0x24, 0x72, 0x1c, 0x32, 0xad, 0xb6, 0xd5, 0xb7, 0x4c,
	0xa2, 0xd4, 0xbf, 0x49, 0xa0, 0xb4, 0xe8, 0x3e, 0xb1, 0x05, 0xf9, 0x84, 0x86, 0xf1, 0x5f, 0xbe,
	0xe6, 0xe5, 0xef, 0x53, 0x75, 0x7b, 0x55, 0x8a, 0xfe, 0x52, 0x47, 0x90, 0x8b, 0x44, 0x86, 0x15,
	0x0e, 0x5a, 0xd0, 0x77, 0xb5, 0xbc, 0x14, 0xa7, 0x2f, 0x4d, 0x28, 0xa6, 0x55, 0x8e, 0x3b, 0x0b,
	0xb8, 0x94, 0xf8, 0xd7, 0x54, 0xe9, 0x02, 0x59, 0x14, 0x09, 0xde, 0xe3, 0xc8, 0x35, 0x3a, 0xae,
	0xee, 0xac, 0xcd, 0xd3, 0x8a, 0x67, 0x50, 0x5a, 0xb8, 0x49, 0xfc, 0x7f, 0xf9, 0x41, 0x42, 0x51,
	0xd5, 0xff, 0xd6, 0xa5, 0x69, 0xb9, 0x17, 0x00, 0xb1, 0x36, 0x50, 0xe3, 0xd0, 0x25, 0x75, 0x55,
	0x2b, 0x2b, 0x32, 0xa3, 0xe1, 0xec, 0x43, 0x86, 0xfd, 0xd7, 0x37, 0x7e, 0x05, 0x00, 0x00, 0xff,
	0xff, 0x75, 0xb2, 0xcc, 0x47, 0xfa, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ArdeaClient is the client API for Ardea service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ArdeaClient interface {
	CreateModel(ctx context.Context, in *CreateModelRequest, opts ...grpc.CallOption) (*CreateModelReply, error)
	GetModel(ctx context.Context, in *GetModelRequest, opts ...grpc.CallOption) (*GetModelReply, error)
	GetModelByName(ctx context.Context, in *GetModelByNameRequest, opts ...grpc.CallOption) (*GetModelReply, error)
	UpdateModelState(ctx context.Context, in *UpdateModelStateRequest, opts ...grpc.CallOption) (*UpdateModelStateReply, error)
	UpdateModelPath(ctx context.Context, in *UpdateModelPathRequest, opts ...grpc.CallOption) (*UpdateModelPathReply, error)
	ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsReply, error)
}

type ardeaClient struct {
	cc *grpc.ClientConn
}

func NewArdeaClient(cc *grpc.ClientConn) ArdeaClient {
	return &ardeaClient{cc}
}

func (c *ardeaClient) CreateModel(ctx context.Context, in *CreateModelRequest, opts ...grpc.CallOption) (*CreateModelReply, error) {
	out := new(CreateModelReply)
	err := c.cc.Invoke(ctx, "/ardea.Ardea/CreateModel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ardeaClient) GetModel(ctx context.Context, in *GetModelRequest, opts ...grpc.CallOption) (*GetModelReply, error) {
	out := new(GetModelReply)
	err := c.cc.Invoke(ctx, "/ardea.Ardea/GetModel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ardeaClient) GetModelByName(ctx context.Context, in *GetModelByNameRequest, opts ...grpc.CallOption) (*GetModelReply, error) {
	out := new(GetModelReply)
	err := c.cc.Invoke(ctx, "/ardea.Ardea/GetModelByName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ardeaClient) UpdateModelState(ctx context.Context, in *UpdateModelStateRequest, opts ...grpc.CallOption) (*UpdateModelStateReply, error) {
	out := new(UpdateModelStateReply)
	err := c.cc.Invoke(ctx, "/ardea.Ardea/UpdateModelState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ardeaClient) UpdateModelPath(ctx context.Context, in *UpdateModelPathRequest, opts ...grpc.CallOption) (*UpdateModelPathReply, error) {
	out := new(UpdateModelPathReply)
	err := c.cc.Invoke(ctx, "/ardea.Ardea/UpdateModelPath", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ardeaClient) ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsReply, error) {
	out := new(ListModelsReply)
	err := c.cc.Invoke(ctx, "/ardea.Ardea/ListModels", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArdeaServer is the server API for Ardea service.
type ArdeaServer interface {
	CreateModel(context.Context, *CreateModelRequest) (*CreateModelReply, error)
	GetModel(context.Context, *GetModelRequest) (*GetModelReply, error)
	GetModelByName(context.Context, *GetModelByNameRequest) (*GetModelReply, error)
	UpdateModelState(context.Context, *UpdateModelStateRequest) (*UpdateModelStateReply, error)
	UpdateModelPath(context.Context, *UpdateModelPathRequest) (*UpdateModelPathReply, error)
	ListModels(context.Context, *ListModelsRequest) (*ListModelsReply, error)
}

// UnimplementedArdeaServer can be embedded to have forward compatible implementations.
type UnimplementedArdeaServer struct {
}

func (*UnimplementedArdeaServer) CreateModel(ctx context.Context, req *CreateModelRequest) (*CreateModelReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateModel not implemented")
}
func (*UnimplementedArdeaServer) GetModel(ctx context.Context, req *GetModelRequest) (*GetModelReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetModel not implemented")
}
func (*UnimplementedArdeaServer) GetModelByName(ctx context.Context, req *GetModelByNameRequest) (*GetModelReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetModelByName not implemented")
}
func (*UnimplementedArdeaServer) UpdateModelState(ctx context.Context, req *UpdateModelStateRequest) (*UpdateModelStateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateModelState not implemented")
}
func (*UnimplementedArdeaServer) UpdateModelPath(ctx context.Context, req *UpdateModelPathRequest) (*UpdateModelPathReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateModelPath not implemented")
}
func (*UnimplementedArdeaServer) ListModels(ctx context.Context, req *ListModelsRequest) (*ListModelsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListModels not implemented")
}

func RegisterArdeaServer(s *grpc.Server, srv ArdeaServer) {
	s.RegisterService(&_Ardea_serviceDesc, srv)
}

func _Ardea_CreateModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArdeaServer).CreateModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ardea.Ardea/CreateModel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArdeaServer).CreateModel(ctx, req.(*CreateModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ardea_GetModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArdeaServer).GetModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ardea.Ardea/GetModel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArdeaServer).GetModel(ctx, req.(*GetModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ardea_GetModelByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModelByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArdeaServer).GetModelByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ardea.Ardea/GetModelByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArdeaServer).GetModelByName(ctx, req.(*GetModelByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ardea_UpdateModelState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateModelStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArdeaServer).UpdateModelState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ardea.Ardea/UpdateModelState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArdeaServer).UpdateModelState(ctx, req.(*UpdateModelStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ardea_UpdateModelPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateModelPathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArdeaServer).UpdateModelPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ardea.Ardea/UpdateModelPath",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArdeaServer).UpdateModelPath(ctx, req.(*UpdateModelPathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ardea_ListModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArdeaServer).ListModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ardea.Ardea/ListModels",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArdeaServer).ListModels(ctx, req.(*ListModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Ardea_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ardea.Ardea",
	HandlerType: (*ArdeaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateModel",
			Handler:    _Ardea_CreateModel_Handler,
		},
		{
			MethodName: "GetModel",
			Handler:    _Ardea_GetModel_Handler,
		},
		{
			MethodName: "GetModelByName",
			Handler:    _Ardea_GetModelByName_Handler,
		},
		{
			MethodName: "UpdateModelState",
			Handler:    _Ardea_UpdateModelState_Handler,
		},
		{
			MethodName: "UpdateModelPath",
			Handler:    _Ardea_UpdateModelPath_Handler,
		},
		{
			MethodName: "ListModels",
			Handler:    _Ardea_ListModels_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ardea.proto",
}
